/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface DeleteFolderResponse {
    /** ID of the deleted folder */
    id?: string;
    /** Name of the deleted folder */
    name?: string;
    /** Description of the deleted folder */
    description?: string;
    /** Last update timestamp of the deleted folder */
    updatedAt?: Date;
}
