/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UpsertFolderResponse {
    /** ID of the created or updated folder */
    id?: string;
    /** Name of the folder */
    name?: string;
    /** Description of the folder */
    description?: string;
    /** Timestamp of when the folder was updated */
    updatedAt?: Date;
}
