/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateUserGroupRequest: core.serialization.Schema<
    serializers.CreateUserGroupRequest.Raw,
    RulebricksApi.CreateUserGroupRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace CreateUserGroupRequest {
    export interface Raw {
        name: string;
        description?: string | null;
    }
}
