/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const CreateUserGroupRequest: core.serialization.Schema<serializers.CreateUserGroupRequest.Raw, RulebricksApi.CreateUserGroupRequest>;
export declare namespace CreateUserGroupRequest {
    interface Raw {
        name: string;
        description?: string | null;
    }
}
