/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RulebricksApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const InviteRequest: core.serialization.Schema<serializers.InviteRequest.Raw, RulebricksApi.InviteRequest>;
export declare namespace InviteRequest {
    interface Raw {
        email: string;
        role?: serializers.InviteRequestRole.Raw | null;
        accessGroups?: string[] | null;
    }
}
