// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "slug",
 *         testId: "testId"
 *     }
 */
export interface DeleteFlowsRequest {
    /** The unique identifier for the resource. */
    slug: string;
    /** The ID of the test. */
    testId: string;
}
