/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const DeleteFolderRequest: core.serialization.Schema<serializers.DeleteFolderRequest.Raw, RulebricksApi.DeleteFolderRequest>;
export declare namespace DeleteFolderRequest {
    interface Raw {
        id: string;
    }
}
