/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const DeleteRuleRequest: core.serialization.Schema<serializers.DeleteRuleRequest.Raw, RulebricksApi.DeleteRuleRequest>;
export declare namespace DeleteRuleRequest {
    interface Raw {
        id: string;
    }
}
