/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RulebricksApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const ImportRuleRequest: core.serialization.Schema<serializers.ImportRuleRequest.Raw, RulebricksApi.ImportRuleRequest>;
export declare namespace ImportRuleRequest {
    interface Raw {
        rule: Record<string, unknown>;
    }
}
