/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ImportRuleRequest: core.serialization.Schema<
    serializers.ImportRuleRequest.Raw,
    RulebricksApi.ImportRuleRequest
> = core.serialization.object({
    rule: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace ImportRuleRequest {
    export interface Raw {
        rule: Record<string, unknown>;
    }
}
