/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpsertFolderRequest: core.serialization.Schema<
    serializers.UpsertFolderRequest.Raw,
    RulebricksApi.UpsertFolderRequest
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace UpsertFolderRequest {
    export interface Raw {
        id?: string | null;
        name: string;
        description?: string | null;
    }
}
