/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface DeleteRuleRequest {
    /** The ID of the rule to delete. */
    id?: string;
}
