/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "abc123"
 *     }
 */
export interface DeleteFolderRequest {
    /** ID of the folder to delete */
    id: string;
}
