// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         root_type: "rule",
 *         root_ids: ["pricing-rule", "eligibility-check"],
 *         include_downstream: false
 *     }
 */
export interface ExportManifestRequest {
    /** The type of root asset to export. All dependencies will be included. */
    root_type: ExportManifestRequest.RootType;
    /** Array of IDs for the root assets to export. Dependencies are automatically resolved. */
    root_ids: string[];
    /** For context exports, whether to include rules and flows bound to the context. */
    include_downstream?: boolean;
    /** Optional name for the exported manifest. */
    manifest_name?: string;
    /** Optional description for the exported manifest. */
    manifest_description?: string;
    /** If true, returns a preview of what would be exported without the full data. */
    preview_only?: boolean;
}

export namespace ExportManifestRequest {
    /** The type of root asset to export. All dependencies will be included. */
    export const RootType = {
        Rule: "rule",
        Flow: "flow",
        Context: "context",
        Value: "value",
    } as const;
    export type RootType = (typeof RootType)[keyof typeof RootType];
}
