// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         manifest: {
 *             version: "1.0",
 *             rules: [{
 *                     "name": "Pricing Rule",
 *                     "slug": "pricing-rule"
 *                 }],
 *             flows: [{
 *                     "name": "Onboarding Flow",
 *                     "slug": "onboarding-flow"
 *                 }],
 *             entities: [{
 *                     "name": "Customer",
 *                     "slug": "customer"
 *                 }],
 *             values: [{
 *                     "name": "tax_rate",
 *                     "value": 0.08
 *                 }]
 *         },
 *         conflict_strategy: "update"
 *     }
 */
export interface ImportManifestRequest {
    /** The RBM manifest object containing assets to import. Asset objects inside the manifest intentionally preserve `.rbm`/database casing so exported manifests can be imported without rewriting asset payloads. */
    manifest: ImportManifestRequest.Manifest;
    /** How to handle conflicts with existing assets. 'update' overwrites, 'skip' ignores, 'error' fails. */
    conflict_strategy?: ImportManifestRequest.ConflictStrategy;
    /** Optional folder name to place imported assets into. Created if it doesn't exist. */
    target_folder_name?: string;
    /** Optional mapping for legacy flow imports to reuse existing rules. */
    legacy_rule_mapping?: Record<string, ImportManifestRequest.LegacyRuleMapping.Value>;
}

export namespace ImportManifestRequest {
    /**
     * The RBM manifest object containing assets to import. Asset objects inside the manifest intentionally preserve `.rbm`/database casing so exported manifests can be imported without rewriting asset payloads.
     */
    export interface Manifest {
        /** Manifest format version. */
        version?: string | undefined;
        /** Rules to import. */
        rules?: Record<string, unknown>[] | undefined;
        /** Flows to import. */
        flows?: Record<string, unknown>[] | undefined;
        /** Contexts to import. */
        entities?: Record<string, unknown>[] | undefined;
        /** Dynamic values to import. */
        values?: Record<string, unknown>[] | undefined;
    }

    /** How to handle conflicts with existing assets. 'update' overwrites, 'skip' ignores, 'error' fails. */
    export const ConflictStrategy = {
        Update: "update",
        Skip: "skip",
        Error: "error",
    } as const;
    export type ConflictStrategy = (typeof ConflictStrategy)[keyof typeof ConflictStrategy];

    export namespace LegacyRuleMapping {
        export interface Value {
            action?: Value.Action | undefined;
            rule_id?: string | undefined;
        }

        export namespace Value {
            export const Action = {
                Reuse: "reuse",
                Create: "create",
            } as const;
            export type Action = (typeof Action)[keyof typeof Action];
        }
    }
}
