/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         id: "id",
 *         createdAt: new Date("2024-01-15T09:30:00.000Z"),
 *         slug: "slug",
 *         updatedAt: new Date("2024-01-15T09:30:00.000Z"),
 *         testRequest: {
 *             "key": "value"
 *         },
 *         name: "name",
 *         description: "description",
 *         requestSchema: [],
 *         responseSchema: [],
 *         sampleRequest: {
 *             "key": "value"
 *         },
 *         sampleResponse: {
 *             "key": "value"
 *         },
 *         conditions: [],
 *         published: true,
 *         history: []
 *     }
 */
export interface ImportRuleRequest {
    id: string;
    createdAt: Date;
    slug: string;
    updatedAt: Date;
    testRequest: Record<string, unknown>;
    name: string;
    description: string;
    requestSchema: unknown[];
    responseSchema: unknown[];
    sampleRequest: Record<string, unknown>;
    sampleResponse: Record<string, unknown>;
    conditions: unknown[];
    published: boolean;
    history: unknown[];
}
