// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
 *     }
 */
export interface DeleteAdminRequest {
    /** The unique identifier for the context. */
    id: string;
}
