/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface QueryDecisionsRequest {
    /**
     * The slug of the rule to query logs for.
     */
    slug: string;
    /**
     * Start date for the query range (ISO8601 format).
     */
    from?: Date;
    /**
     * End date for the query range (ISO8601 format).
     */
    to?: Date;
    /**
     * Cursor for pagination.
     */
    cursor?: string;
    /**
     * Number of results to return per page.
     */
    limit?: number;
}
