/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as RulebricksApi from "../../..";
export declare namespace Tests {
    interface Options {
        environment: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
/**
 * Administrative operations for programmatically managing test suites for rules and flows
 */
export declare class Tests {
    protected readonly _options: Tests.Options;
    constructor(_options: Tests.Options);
    /**
     * Retrieves a list of tests associated with the rule identified by the slug.
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.listRuleTests("slug")
     */
    listRuleTests(slug: string, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.ListRuleTestsResponseItem[]>;
    /**
     * Adds a new test to the test suite of a rule identified by the slug.
     * @throws {@link RulebricksApi.BadRequestError}
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.createRuleTest("slug", {
     *         name: "Test 3",
     *         request: {
     *             "param1": "value1"
     *         },
     *         response: {
     *             "status": "success"
     *         },
     *         critical: true
     *     })
     */
    createRuleTest(slug: string, request: RulebricksApi.CreateRuleTestRequest, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.CreateRuleTestResponse>;
    /**
     * Deletes a test from the test suite of a rule identified by the slug.
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.deleteRuleTest("slug", "testId")
     */
    deleteRuleTest(slug: string, testId: string, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.DeleteRuleTestResponse>;
    /**
     * Retrieves a list of tests associated with the flow identified by the slug.
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.listFlowTests("slug")
     */
    listFlowTests(slug: string, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.ListFlowTestsResponseItem[]>;
    /**
     * Adds a new test to the test suite of a flow identified by the slug.
     * @throws {@link RulebricksApi.BadRequestError}
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.createFlowTest("slug", {
     *         name: "Test 3",
     *         request: {
     *             "param1": "value1"
     *         },
     *         response: {
     *             "status": "success"
     *         },
     *         critical: true
     *     })
     */
    createFlowTest(slug: string, request: RulebricksApi.CreateFlowTestRequest, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.CreateFlowTestResponse>;
    /**
     * Deletes a test from the test suite of a flow identified by the slug.
     * @throws {@link RulebricksApi.NotFoundError}
     * @throws {@link RulebricksApi.InternalServerError}
     *
     * @example
     *     await rulebricksApi.tests.deleteFlowTest("slug", "testId")
     */
    deleteFlowTest(slug: string, testId: string, requestOptions?: Tests.RequestOptions): Promise<RulebricksApi.DeleteFlowTestResponse>;
}
