// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { FlowsClient } from "../resources/flows/client/Client.js";
import { RulesClient } from "../resources/rules/client/Client.js";

export declare namespace TestsClient {
    export type Options = BaseClientOptions;
}

export class TestsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TestsClient.Options>;
    protected _rules: RulesClient | undefined;
    protected _flows: FlowsClient | undefined;

    constructor(options: TestsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get rules(): RulesClient {
        return (this._rules ??= new RulesClient(this._options));
    }

    public get flows(): FlowsClient {
        return (this._flows ??= new FlowsClient(this._options));
    }
}
