/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as RulebricksApi from "..";
export declare class ForbiddenError extends errors.RulebricksApiError {
    constructor(body: RulebricksApi.ForbiddenErrorBody);
}
