"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RulebricksApiTimeoutError = void 0;
class RulebricksApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, RulebricksApiTimeoutError.prototype);
    }
}
exports.RulebricksApiTimeoutError = RulebricksApiTimeoutError;
