// This file was auto-generated by Fern from our API Definition.

export const QueryDecisionsRequestIncludeTraces = {
    True: "true",
    False: "false",
} as const;
export type QueryDecisionsRequestIncludeTraces =
    (typeof QueryDecisionsRequestIncludeTraces)[keyof typeof QueryDecisionsRequestIncludeTraces];
