// This file was auto-generated by Fern from our API Definition.

export const QueryDecisionsRequestCount = {
    True: "true",
    False: "false",
} as const;
export type QueryDecisionsRequestCount = (typeof QueryDecisionsRequestCount)[keyof typeof QueryDecisionsRequestCount];
