// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../../index.js";

/**
 * @example
 *     {
 *         slug: "loan-application",
 *         body: [{
 *                 "loan_id": "APP-1",
 *                 "amount": 12000
 *             }, {
 *                 "loan_id": "APP-2",
 *                 "amount": 7300
 *             }]
 *     }
 */
export interface BulkIngestContextsRequest {
    /** The unique slug for the context. */
    slug: string;
    /** Comma-separated list of per-instance fields to include in results (instance_id is always present). Omit to include everything. Valid fields: positions, is_new, status, have, need, state, expires_at, executions, executed, triggered, reason. Useful for keeping response size proportional to outcomes rather than data volume, e.g. include=status,executed. */
    include?: string;
    body: Rulebricks.DynamicRequestPayload[];
}
