// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "customer",
 *         instance: "cust-12345"
 *     }
 */
export interface CascadeContextRequest {
    /** The unique slug for the context. */
    slug: string;
    /** The unique identifier for the context instance. */
    instance: string;
    /** Maximum depth for cascading evaluations. */
    maxDepth?: number;
}
