// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../../index.js";

/**
 * @example
 *     {
 *         slug: "customer",
 *         instance: "cust-12345",
 *         flowSlug: "onboarding-flow",
 *         body: {}
 *     }
 */
export interface ExecuteContextsRequest {
    /** The unique slug for the context. */
    slug: string;
    /** The unique identifier for the context instance. */
    instance: string;
    /** The unique slug for the flow. */
    flowSlug: string;
    body: Rulebricks.SolveContextFlowRequest;
}
