// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "customer",
 *         instance: "cust-12345"
 *     }
 */
export interface GetHistoryContextsRequest {
    /** The unique slug for the context. */
    slug: string;
    /** The unique identifier for the context instance. */
    instance: string;
    /** Filter history to a specific field. */
    field?: string;
    /** Maximum number of history entries to return. */
    limit?: number;
}
