// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "customer",
 *         instance: "cust-12345",
 *         flowSlug: "onboarding-flow"
 *     }
 */
export interface SolveContextFlowRequest {
    /** The unique slug for the context. */
    slug: string;
    /** The unique identifier for the context instance. */
    instance: string;
    /** The unique slug for the flow. */
    flowSlug: string;
    /** Additional data to merge with instance state for flow execution. */
    additionalData?: Record<string, unknown>;
    /** Whether to persist derived outputs to the instance. */
    persist?: boolean;
}
