// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../../index.js";

/**
 * @example
 *     {
 *         slug: "slug",
 *         body: {
 *             "body": {
 *                 "name": "Alice Johnson",
 *                 "age": 28,
 *                 "email": "alice.johnson@example.com"
 *             }
 *         }
 *     }
 */
export interface ExecuteFlowsRequest {
    /** The unique identifier for the resource. */
    slug: string;
    body: Rulebricks.DynamicRequestPayload;
}
