/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Rulebricks from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";
import { Rules } from "../resources/rules/client/Client";
import { Flows } from "../resources/flows/client/Client";
import { Folders } from "../resources/folders/client/Client";

export declare namespace Assets {
    export interface Options {
        environment?: core.Supplier<environments.RulebricksEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Administrative operations for managing rules, flows, folders, and usage
 */
export class Assets {
    protected _rules: Rules | undefined;
    protected _flows: Flows | undefined;
    protected _folders: Folders | undefined;

    constructor(protected readonly _options: Assets.Options) {}

    public get rules(): Rules {
        return (this._rules ??= new Rules(this._options));
    }

    public get flows(): Flows {
        return (this._flows ??= new Flows(this._options));
    }

    public get folders(): Folders {
        return (this._folders ??= new Folders(this._options));
    }

    /**
     * Get the rule execution usage of your organization.
     *
     * @param {Assets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.assets.getUsage()
     */
    public async getUsage(requestOptions?: Assets.RequestOptions): Promise<Rulebricks.UsageStatistics> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                "admin/usage",
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.UsageStatistics.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RulebricksError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RulebricksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.RulebricksTimeoutError("Timeout exceeded when calling GET /admin/usage.");
            case "unknown":
                throw new errors.RulebricksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
