/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface DeleteFlowTestResponse {
    /** Unique identifier for the test. */
    id: string;
    /** The name of the test. */
    name: string;
    /** The request object for the test. */
    request: Record<string, unknown>;
    /** The expected response object for the test. */
    response: Record<string, unknown>;
    /** Indicates whether the test is critical. */
    critical: boolean;
    /** Indicates if the test resulted in an error. */
    error: boolean;
    /** Indicates if the test was successful. */
    success: boolean;
    /** The state of the test after execution. */
    testState?: Record<string, unknown>;
    /** The timestamp when the test was last executed. */
    lastExecuted?: Date;
}
