// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../../../../index.js";

/**
 * @example
 *     {
 *         rule: {
 *             id: "11111111-2222-4333-8444-555555555555",
 *             slug: "basic-pricing-rule",
 *             name: "Basic Pricing Rule",
 *             description: "",
 *             createdAt: "2026-02-12T01:29:23.000Z",
 *             updatedAt: "2026-02-12T01:29:23.000Z",
 *             published: false,
 *             _publish: true,
 *             testRequest: {
 *                 "customer_tier": "STANDARD",
 *                 "order_total": 250,
 *                 "expedited": false
 *             },
 *             sampleRequest: {
 *                 "customer_tier": "STANDARD",
 *                 "order_total": 250,
 *                 "expedited": false
 *             },
 *             sampleResponse: {
 *                 "discount_rate": 0,
 *                 "approval_status": "standard"
 *             },
 *             requestSchema: [{
 *                     key: "customer_tier",
 *                     show: true,
 *                     name: "Customer Tier",
 *                     type: "string"
 *                 }, {
 *                     key: "order_total",
 *                     show: true,
 *                     name: "Order Total",
 *                     type: "number"
 *                 }, {
 *                     key: "expedited",
 *                     show: true,
 *                     name: "Expedited",
 *                     type: "boolean"
 *                 }],
 *             responseSchema: [{
 *                     key: "discount_rate",
 *                     show: true,
 *                     name: "Discount Rate",
 *                     type: "number"
 *                 }, {
 *                     key: "approval_status",
 *                     show: true,
 *                     name: "Approval Status",
 *                     type: "string"
 *                 }],
 *             conditions: [{
 *                     request: {
 *                         "customer_tier": {
 *                             op: "equals",
 *                             args: ["VIP"]
 *                         }
 *                     },
 *                     response: {
 *                         "discount_rate": {
 *                             value: 0.2
 *                         },
 *                         "approval_status": {
 *                             value: "priority"
 *                         }
 *                     },
 *                     settings: {
 *                         enabled: true,
 *                         groupId: null,
 *                         priority: 0,
 *                         schedule: []
 *                     }
 *                 }, {
 *                     request: {
 *                         "expedited": {
 *                             op: "equals",
 *                             args: [true]
 *                         }
 *                     },
 *                     response: {
 *                         "discount_rate": {
 *                             value: 0.05
 *                         },
 *                         "approval_status": {
 *                             value: "expedited"
 *                         }
 *                     },
 *                     settings: {
 *                         enabled: true,
 *                         groupId: null,
 *                         priority: 1,
 *                         schedule: []
 *                     }
 *                 }, {
 *                     request: {},
 *                     response: {
 *                         "discount_rate": {
 *                             value: 0
 *                         },
 *                         "approval_status": {
 *                             value: "standard"
 *                         }
 *                     },
 *                     settings: {
 *                         enabled: true,
 *                         groupId: null,
 *                         priority: 2,
 *                         schedule: []
 *                     }
 *                 }],
 *             history: []
 *         }
 *     }
 *
 * @example
 *     {
 *         rule: {
 *             id: "11111111-2222-4333-8444-555555555555",
 *             name: "Updated Rule Name"
 *         }
 *     }
 */
export interface ImportRuleRequest {
    rule: Rulebricks.RuleImportPayload;
}
