// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "2855f8da-2654-4df9-8903-8f797cbfe8eb"
 *     }
 */
export interface PullRulesRequest {
    /** The ID of the rule to export. */
    id: string;
}
