/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface RulesListRequest {
    /**
     * Filter rules by folder name or folder ID
     */
    folder?: string;
}
