/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Role to assign to the user.
 */
export declare type InviteRequestRole = "editor" | "developer";
export declare const InviteRequestRole: {
    readonly Editor: "editor";
    readonly Developer: "developer";
};
