// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Response after triggering a cascade re-evaluation of pending rules/flows.
 */
export interface CascadeContextResponse {
    /** Combined identifier in format 'contextSlug:instanceId'. */
    context?: string;
    /** Results from all cascaded evaluations. */
    cascaded?: Rulebricks.CascadeResult[];
}
