// This file was auto-generated by Fern from our API Definition.

/**
 * Optional request body for triggering a cascade. Currently no properties are used.
 */
export type CascadeContextRequest = Record<string, unknown>;
