// This file was auto-generated by Fern from our API Definition.

export interface ContextRelationshipBase {
    /** The unique identifier for the relationship. */
    id?: string;
    /** The type of relationship. */
    type?: ContextRelationshipBase.Type;
    /** The field key used as the foreign key. */
    foreign_key?: string;
    /** Display name for the relationship. */
    name?: string;
    /** Description of the relationship. */
    description?: string;
    /** When the relationship was created. */
    created_at?: string;
}

export namespace ContextRelationshipBase {
    /** The type of relationship. */
    export const Type = {
        HasMany: "has_many",
        HasOne: "has_one",
        BelongsTo: "belongs_to",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
