// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * The schema definition for a context.
 */
export interface ContextSchema {
    /** User-defined base fields for the context. */
    base?: Rulebricks.ContextSchemaField[] | undefined;
    /** Expression-computed fields. Each entry supplies an `expression` evaluated from base facts, tracked history, and configured relationships. */
    derived?: Rulebricks.ContextSchemaField[] | undefined;
}
