// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Historical values for context instance fields.
 */
export interface ContextInstanceHistory {
    /** Combined identifier in format 'contextSlug:instanceId'. */
    context?: string;
    /** Map of field keys to arrays of historical values, newest first. */
    history?: Record<string, Rulebricks.ContextInstanceHistoryEntry[]>;
}
