// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface ContextDetail extends Rulebricks.ContextBase {
    schema?: Rulebricks.ContextSchema | undefined;
    /** The field key used as the unique identifier for instances. */
    identity_fact?: (string | null) | undefined;
    /** User groups that can interact with this context. */
    user_groups?: (string[] | null) | undefined;
    /** Folder/tag this context belongs to. */
    folder?: (ContextDetail.Folder | null) | undefined;
    /** Rules bound to this context. */
    bound_rules?: ContextDetail.BoundRules.Item[] | undefined;
    /** Flows bound to this context (via their origin rule). */
    bound_flows?: ContextDetail.BoundFlows.Item[] | undefined;
    relationships?: ContextDetail.Relationships | undefined;
    /** When the context was created. */
    created_at?: string | undefined;
    /** When the context was last updated. */
    updated_at?: string | undefined;
}

export namespace ContextDetail {
    /**
     * Folder/tag this context belongs to.
     */
    export interface Folder {
        id?: string | undefined;
        name?: string | undefined;
    }

    export type BoundRules = BoundRules.Item[];

    export namespace BoundRules {
        export interface Item {
            id?: string | undefined;
            name?: string | undefined;
            slug?: string | undefined;
            published?: boolean | undefined;
            /** Version target for this binding: `null` or `latest` follows the current published version, a version number (e.g. `3`) pins that published version, and any other value is a release environment slug resolved at execution time. */
            context_version?: (string | null) | undefined;
        }
    }

    export type BoundFlows = BoundFlows.Item[];

    export namespace BoundFlows {
        export interface Item {
            id?: string | undefined;
            name?: string | undefined;
            slug?: string | undefined;
            published?: boolean | undefined;
            /** Version target for this binding: `null` or `latest` follows the current published version, a version number (e.g. `3`) pins that published version, and any other value is a release environment slug resolved at execution time. */
            context_version?: (string | null) | undefined;
            origin_rule?: (Item.OriginRule | null) | undefined;
        }

        export namespace Item {
            export interface OriginRule {
                id?: string | undefined;
                name?: string | undefined;
                slug?: string | undefined;
            }
        }
    }

    export interface Relationships {
        outgoing?: Rulebricks.ContextRelationshipOutgoing[] | undefined;
        incoming?: Rulebricks.ContextRelationshipIncoming[] | undefined;
    }
}
