// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Response from a context batch: admission counts, per-record rejections, execution outcomes, and the resolved state of every touched instance.
 */
export interface ContextBatchResponse {
    /** The context slug. */
    context?: string | undefined;
    /** Trace ID for the batch request (join key into decision logs when tracing is enabled; always null on the cloud platform). */
    trace_id?: (string | null) | undefined;
    /** Number of distinct instances written (duplicate identities within the batch fold into one). */
    accepted?: number | undefined;
    /** Number of records rejected by validation. */
    rejected?: number | undefined;
    /** Number of successful bound-asset executions. */
    executed?: number | undefined;
    /** Present when data was committed but execution could not run or complete (e.g. queue processing unavailable). Retrying the same chunk once healthy converges. */
    execution_degraded?: string | undefined;
    /** Present when the batch re-evaluated dependent contexts through relationships (one level). Dependents with auto-execution disabled run only previously registered pending work. Each entry summarizes one dependent context's re-evaluation. */
    cascaded?: Rulebricks.ContextCascadeSummary[] | undefined;
    timings?: ContextBatchResponse.Timings | undefined;
    /** Per-record validation failures, referencing positions in the submitted array. */
    rejections?: ContextBatchResponse.Rejections.Item[] | undefined;
    /** One entry per touched instance. Fields beyond instance_id can be narrowed with the include query parameter. */
    results?: ContextBatchResponse.Results.Item[] | undefined;
}

export namespace ContextBatchResponse {
    export interface Timings {
        total_ms?: number | undefined;
        ingest_ms?: number | undefined;
    }

    export type Rejections = Rejections.Item[];

    export namespace Rejections {
        export interface Item {
            position?: number | undefined;
            error?: string | undefined;
        }
    }

    export type Results = Results.Item[];

    export namespace Results {
        export interface Item {
            instance_id?: string | undefined;
            /** Positions in the submitted array that folded into this instance. */
            positions?: number[] | undefined;
            is_new?: boolean | undefined;
            status?: Item.Status | undefined;
            have?: string[] | undefined;
            need?: string[] | undefined;
            /** Resolved instance state after merging and any executions, including computed facts. */
            state?: Record<string, unknown> | undefined;
            expires_at?: (string | null) | undefined;
            /** Per-asset record of the last run: input hash, status, timestamp, trace IDs, error. */
            executions?: Record<string, unknown> | undefined;
            /** Assets evaluated for this instance in this request. */
            executed?: Item.Executed.Item[] | undefined;
            /** True when at least one bound asset was considered for this instance - including assets that settled as skipped_already_run. False (with a reason) when nothing was attempted. */
            triggered?: boolean | undefined;
            /** Present when triggered is false (executed is empty): not_ready = required facts still missing; inputs_unchanged = the instance is complete but no bound asset had satisfiable inputs to attempt; no_bound_assets = the context has no published bound rules or flows; auto_execute_disabled = the context's auto_execute_decisions is off; execution_unavailable = the execution backend was unreachable. Note: assets whose inputs are unchanged since their last successful run appear as executed entries with status skipped_already_run and leave triggered true. */
            reason?: Item.Reason | undefined;
        }

        export namespace Item {
            export const Status = {
                Complete: "complete",
                Pending: "pending",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export type Executed = Executed.Item[];

            export namespace Executed {
                export interface Item {
                    type?: Item.Type | undefined;
                    slug?: string | undefined;
                    status?: Item.Status | undefined;
                    error?: string | undefined;
                    written_to_context?: string[] | undefined;
                }

                export namespace Item {
                    export const Type = {
                        Rule: "rule",
                        Flow: "flow",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                    export const Status = {
                        Success: "success",
                        EvaluationError: "evaluation_error",
                        InfrastructureError: "infrastructure_error",
                        SkippedAlreadyRun: "skipped_already_run",
                    } as const;
                    export type Status = (typeof Status)[keyof typeof Status];
                }
            }

            /** Present when triggered is false (executed is empty): not_ready = required facts still missing; inputs_unchanged = the instance is complete but no bound asset had satisfiable inputs to attempt; no_bound_assets = the context has no published bound rules or flows; auto_execute_disabled = the context's auto_execute_decisions is off; execution_unavailable = the execution backend was unreachable. Note: assets whose inputs are unchanged since their last successful run appear as executed entries with status skipped_already_run and leave triggered true. */
            export const Reason = {
                NotReady: "not_ready",
                InputsUnchanged: "inputs_unchanged",
                NoBoundAssets: "no_bound_assets",
                AutoExecuteDisabled: "auto_execute_disabled",
                ExecutionUnavailable: "execution_unavailable",
            } as const;
            export type Reason = (typeof Reason)[keyof typeof Reason];
        }
    }
}
