// This file was auto-generated by Fern from our API Definition.

/**
 * A single history entry for a field value.
 */
export interface ContextInstanceHistoryEntry {
    /** When this value was recorded. */
    timestamp?: string;
    /** The field value at this point in time. */
    value?: unknown;
}
