// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface ContextRelationshipsResponse {
    /** The context these relationships belong to. */
    context?: ContextRelationshipsResponse.Context | undefined;
    outgoing?: Rulebricks.ContextRelationshipOutgoing[] | undefined;
    incoming?: Rulebricks.ContextRelationshipIncoming[] | undefined;
}

export namespace ContextRelationshipsResponse {
    /**
     * The context these relationships belong to.
     */
    export interface Context {
        id?: string | undefined;
        name?: string | undefined;
        slug?: string | undefined;
    }
}
