// This file was auto-generated by Fern from our API Definition.

export interface ContextRelationshipBase {
    /** The unique identifier for the relationship. */
    id?: string | undefined;
    /** The type of relationship. */
    relation_type?: ContextRelationshipBase.RelationType | undefined;
    /** The field key used as the foreign key. */
    foreign_key_fact?: string | undefined;
    /** Runtime relationship key used by derived expressions. It is normalized to lowercase snake_case. */
    name?: string | undefined;
    /** Description of the relationship. */
    description?: string | undefined;
    /** When the relationship was created. */
    created_at?: string | undefined;
}

export namespace ContextRelationshipBase {
    /** The type of relationship. */
    export const RelationType = {
        HasMany: "has_many",
        HasOne: "has_one",
        BelongsTo: "belongs_to",
    } as const;
    export type RelationType = (typeof RelationType)[keyof typeof RelationType];
}
