// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface ContextRelationshipOutgoing extends Rulebricks.ContextRelationshipBase {
    targetContext?: ContextRelationshipOutgoing.TargetContext;
}

export namespace ContextRelationshipOutgoing {
    export interface TargetContext {
        id?: string;
        name?: string;
        slug?: string;
    }
}
