// This file was auto-generated by Fern from our API Definition.

/**
 * A field definition within a context schema.
 */
export interface ContextSchemaField {
    /** The unique key for this field. */
    key?: string;
    /** Display name for this field. */
    name?: string;
    /** Description of this field. */
    description?: string;
    /** Data type of this field. 'function' type fields compute values dynamically. */
    type?: ContextSchemaField.Type;
    /** Default value for this field. */
    defaultValue?: unknown | null;
    /** Whether this field is derived from rule/flow outputs. */
    derived?: boolean;
    /** The rule ID that derives this field (if derived). */
    sourceRule?: string | null;
    /** The flow ID that derives this field (if derived). */
    sourceFlow?: string | null;
    /** The source field key in the rule/flow output. */
    sourceField?: string | null;
}

export namespace ContextSchemaField {
    /** Data type of this field. 'function' type fields compute values dynamically. */
    export const Type = {
        String: "string",
        Number: "number",
        Boolean: "boolean",
        Date: "date",
        List: "list",
        Function: "function",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
