// This file was auto-generated by Fern from our API Definition.

/**
 * The current state of a context instance.
 */
export interface ContextInstanceState {
    /** Combined identifier in format 'contextSlug:instanceId'. */
    context?: string | undefined;
    /** The current base fact values for this instance (derived facts are reported separately under `derived`; note that POST responses combine both under `state`). */
    state?: Record<string, unknown> | undefined;
    /** Expression-computed derived fact values (recomputed on read from base facts, relations, and history). */
    derived?: Record<string, unknown> | undefined;
    /** Whether all required fields are present ('complete') or some are missing ('pending'). */
    status?: ContextInstanceState.Status | undefined;
    /** List of field keys that are currently populated. */
    have?: string[] | undefined;
    /** List of required field keys that are missing (empty when status is 'complete'). */
    need?: string[] | undefined;
    /** Related instance data, present only when include_relations was requested. Keys are relationship names; has_many relations map to a list of related instance states, has_one/belongs_to to a single state or null. */
    relations?: Record<string, unknown> | undefined;
    /** Per-asset execution metadata, present after a bound rule or flow has run for this instance. */
    executions?: Record<string, unknown> | undefined;
    /** When the instance was first created. */
    created_at?: string | undefined;
    /** When the instance was last updated. */
    updated_at?: string | undefined;
    /** When the instance will expire based on context TTL. */
    expires_at?: (string | null) | undefined;
}

export namespace ContextInstanceState {
    /** Whether all required fields are present ('complete') or some are missing ('pending'). */
    export const Status = {
        Complete: "complete",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
