// This file was auto-generated by Fern from our API Definition.

/**
 * A pending dependency. Fact dependencies identify the context instance and missing fields; relationship dependencies also include the relationship name and derived facts that depend on it.
 */
export interface ContextWaitingOn {
    /** Context slug that must supply the dependency. May be null when relationship metadata cannot resolve a target. */
    context?: (string | null) | undefined;
    /** Context instance identity for direct fact dependencies. */
    instance?: string | undefined;
    /** Missing fact paths, or [`*`] for a relationship dependency. */
    fields?: string[] | undefined;
    /** Relationship name for relationship dependencies. */
    relation?: string | undefined;
    /** Derived fact keys waiting on this relationship. */
    dependentDerivedFields?: string[] | undefined;
}
