// This file was auto-generated by Fern from our API Definition.

/**
 * Summary of the newly created context.
 */
export interface CreateContextResponse {
    /** Unique identifier of the context. */
    id?: string | undefined;
    /** URL-safe slug generated from the name (suffixed on collision). */
    slug?: string | undefined;
    /** The name of the context. */
    name?: string | undefined;
    /** Creation timestamp. */
    created_at?: string | undefined;
}
