/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTestRequest {
    /** The name of the test. */
    name: string;
    /** The request object for the test. */
    request: Record<string, unknown>;
    /** The expected response object for the test. */
    response: Record<string, unknown>;
    /** Indicates whether the test is critical. */
    critical: boolean;
}
