// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Rule/flow execution log entry with request, response, and decision details.
 */
export interface DecisionLog {
    /** When the rule/flow was executed. */
    timestamp?: string | null;
    /** Name of the rule or flow that was executed. */
    name?: string | null;
    /** API endpoint that was called. */
    endpoint?: string | null;
    /** HTTP status code of the response. */
    status?: number | null;
    /** The request payload sent to the rule/flow. Can be an object for single requests or an array for bulk operations. */
    request?: DecisionLog.Request | null;
    /** The response payload returned by the rule/flow. Can be an object for single responses or an array for bulk operations. */
    response?: Rulebricks.DecisionLogResponse | null;
    /** Decision details including matched conditions, rows, and evaluation metadata. */
    decision?: Record<string, unknown> | null;
    /** Error message if the execution failed. */
    error?: string | null;
    /** Whether the request/response data was truncated due to size limits. */
    abbreviated?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace DecisionLog {
    /**
     * The request payload sent to the rule/flow. Can be an object for single requests or an array for bulk operations.
     */
    export type Request = Record<string, unknown> | Record<string, unknown>[];
}
