// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Rule/flow execution log entry with request, response, and decision details.
 */
export interface DecisionLog {
    /** When the rule/flow was executed. */
    timestamp?: (string | null) | undefined;
    /** Name of the rule or flow that was executed. */
    name?: (string | null) | undefined;
    /** API endpoint that was called. */
    endpoint?: (string | null) | undefined;
    /** HTTP status code of the response. */
    status?: (number | null) | undefined;
    /** The request payload sent to the rule/flow. Can be an object for single requests or an array for bulk operations. */
    request?: (DecisionLog.Request | null) | undefined;
    /** The response payload returned by the rule/flow. Can be an object for single responses or an array for bulk operations. */
    response?: (Rulebricks.DecisionLogResponse | null) | undefined;
    /** Decision details including matched conditions, rows, and evaluation metadata. API-owned metadata keys are normalized to snake_case where known, including rule, flow, context, item, and correlation fields such as `rule_id`, `flow_execution_id`, `root_flow_execution_id`, `parallel_execution_id`, `context_instance_id`, `item_indexes`, and `item_execution_ids` (bulk flow runs' per-item execution ids, aligned 1:1 with the request array). Rule decisions also expose the bounded execution-time vocabulary snapshot under `referenced_values`; `referenced_values_truncated` indicates that one or more payloads or entries were omitted. Executions backed by a frozen published vocabulary include its asset/version pointer under `value_world`. User-defined request/response schema keys are preserved. */
    decision?: (Record<string, unknown> | null) | undefined;
    /** Observability (OpenTelemetry) trace ID for this execution. Populated on self-hosted deployments only; always null on cloud. */
    trace_id?: (string | null) | undefined;
    /** Decompressed execution path trace for flow records: the executed steps with their inputs and outputs. An object for single flow runs, or a null-aligned array (1:1 with the request array) for bulk runs. Only present when `include_traces=true`; null for non-flow records, runs without a stored trace, and traces dropped by the size cap (see the decision's `path_trace_omitted`). */
    path_trace?: (DecisionLog.PathTrace | null) | undefined;
    /** Only present when `item_filter` was supplied and this record is bulk-shaped: the original zero-based positions (within this record's stored request array) of the items that matched the filter, in order. The record's `request`, `response`, and index-aligned decision fields are sliced to these items; `decision.item_count` keeps the original total. Empty when no items matched. On self-hosted deployments where large bulk runs are logged in chunks, the absolute position within the original API call is `decision.logChunk.offset` plus this value. */
    matched_items?: number[] | undefined;
    /** Error message if the execution failed. */
    error?: (string | null) | undefined;
    /** Whether the request/response data was truncated due to size limits or unavailable payload columns. Responses carry full payloads whenever they were stored. */
    abbreviated?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace DecisionLog {
    /**
     * The request payload sent to the rule/flow. Can be an object for single requests or an array for bulk operations.
     */
    export type Request = Record<string, unknown> | Record<string, unknown>[];
    /**
     * Decompressed execution path trace for flow records: the executed steps with their inputs and outputs. An object for single flow runs, or a null-aligned array (1:1 with the request array) for bulk runs. Only present when `include_traces=true`; null for non-flow records, runs without a stored trace, and traces dropped by the size cap (see the decision's `path_trace_omitted`).
     */
    export type PathTrace = Record<string, unknown> | (Record<string, unknown> | null)[];
}
