/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RulebricksApi from "../index";

export interface DecisionLogDecision {
    conditions?: Record<string, RulebricksApi.DecisionLogDecisionConditionsItemValue>[];
    successIdxs?: number[];
}
