/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RulebricksApi from "../index";
export interface DecisionLogResponse {
    data?: RulebricksApi.DecisionLog[];
    /** Pagination cursor for next page */
    cursor?: string;
}
