// This file was auto-generated by Fern from our API Definition.

export interface DeleteObjectResponse {
    message?: string | undefined;
    values?: DeleteObjectResponse.Values | undefined;
}

export namespace DeleteObjectResponse {
    export interface Values {
        /** Generated values that lost their management lock. */
        detached?: number | undefined;
        /** Generated values archived (0 when values=detach). */
        archived?: number | undefined;
    }
}
