// This file was auto-generated by Fern from our API Definition.

export interface DeleteRelationshipResponse {
    /** Success message. */
    message?: string | undefined;
    /** The ID of the deleted relationship. */
    id?: string | undefined;
}
