/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Dynamic response payload from rule execution. Structure depends on rule configuration.
 */
export type DynamicResponsePayload = Record<string, unknown>;
