/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RulebricksApi from "../index";

export type DynamicValue =
    | RulebricksApi.DynamicValue.String
    | RulebricksApi.DynamicValue.Number
    | RulebricksApi.DynamicValue.Boolean
    | RulebricksApi.DynamicValue.List;

export namespace DynamicValue {
    export interface String extends RulebricksApi.StringValue {
        type: "string";
    }

    export interface Number extends RulebricksApi.NumberValue {
        type: "number";
    }

    export interface Boolean extends RulebricksApi.BooleanValue {
        type: "boolean";
    }

    export interface List extends RulebricksApi.ListValue {
        type: "list";
    }
}
