// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface DynamicValue {
    /** Unique identifier for the dynamic value. */
    id: string;
    /** Name of the dynamic value (may include dot notation for nested properties). */
    name: string;
    /** Type identifier for the value (e.g., 'string', 'number', 'boolean', 'list', 'function', etc.) */
    type: string;
    /** The actual value - can be any valid JSON type */
    value?: DynamicValue.Value;
    /** Rules that use this dynamic value (only included when 'include=usage' parameter is used). */
    usages?: Rulebricks.RuleUsage[];
    /** User groups assigned to this value. */
    user_groups?: string[];
}

export namespace DynamicValue {
    /**
     * The actual value - can be any valid JSON type
     */
    export type Value = string | number | boolean | unknown[] | Record<string, unknown>;
}
