/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RulebricksApi from "../index";

export interface DynamicValueBase {
    /** Unique identifier for the dynamic value. */
    id?: string;
    /** Name of the dynamic value. */
    name?: string;
    /** Rules that use this dynamic value. */
    usages?: RulebricksApi.RuleUsage[];
    /** Access groups assigned to this value. */
    accessGroups?: string[];
}
