// This file was auto-generated by Fern from our API Definition.

export interface ExportManifestResponse {
    /** Whether the export completed successfully. */
    success?: boolean | undefined;
    /** The exported manifest data. The wrapper uses snake_case, while asset objects inside `contexts`, `values`, `rules`, and `flows` intentionally preserve `.rbm`/database casing for round-trip compatibility. When the request sets `compress: true`, this field is instead the compress-json array encoding of the same manifest (a JSON array, not the object described below). */
    manifest?: ExportManifestResponse.Manifest | undefined;
    /** Error message if export failed. */
    error?: string | undefined;
}

export namespace ExportManifestResponse {
    /**
     * The exported manifest data. The wrapper uses snake_case, while asset objects inside `contexts`, `values`, `rules`, and `flows` intentionally preserve `.rbm`/database casing for round-trip compatibility. When the request sets `compress: true`, this field is instead the compress-json array encoding of the same manifest (a JSON array, not the object described below).
     */
    export interface Manifest {
        /** Manifest format version. */
        version?: string | undefined;
        /** Manifest name. */
        name?: string | undefined;
        /** Manifest description. */
        description?: string | undefined;
        exported_at?: string | undefined;
        /** Exported contexts. */
        contexts?: Record<string, unknown>[] | undefined;
        /** Exported vocabulary values. */
        values?: Record<string, unknown>[] | undefined;
        /** Exported rules. */
        rules?: Record<string, unknown>[] | undefined;
        /** Exported flows. */
        flows?: Record<string, unknown>[] | undefined;
    }
}
