// This file was auto-generated by Fern from our API Definition.

export interface ExportManifestResponse {
    /** Whether the export completed successfully. */
    success?: boolean;
    /** The exported manifest data. */
    manifest?: ExportManifestResponse.Manifest;
    /** Error message if export failed. */
    error?: string;
}

export namespace ExportManifestResponse {
    /**
     * The exported manifest data.
     */
    export interface Manifest {
        /** Manifest format version. */
        version?: string;
        /** Manifest name. */
        name?: string;
        /** Manifest description. */
        description?: string;
        exported_at?: string;
        /** Exported contexts. */
        contexts?: Record<string, unknown>[];
        /** Exported dynamic values. */
        values?: Record<string, unknown>[];
        /** Exported rules. */
        rules?: Record<string, unknown>[];
        /** Exported flows. */
        flows?: Record<string, unknown>[];
    }
}
