// This file was auto-generated by Fern from our API Definition.

export interface ExportManifestPreviewResponse {
    /** Whether the preview completed successfully. */
    success?: boolean | undefined;
    /** Preview of assets that would be exported. The preview wrapper uses snake_case, while asset items intentionally preserve `.rbm`/database casing (for example, `valueType` and `updatedAt`) because the same items feed manifest preview/import UI. */
    preview?: ExportManifestPreviewResponse.Preview | undefined;
    /** Error message if preview failed. */
    error?: string | undefined;
}

export namespace ExportManifestPreviewResponse {
    /**
     * Preview of assets that would be exported. The preview wrapper uses snake_case, while asset items intentionally preserve `.rbm`/database casing (for example, `valueType` and `updatedAt`) because the same items feed manifest preview/import UI.
     */
    export interface Preview {
        counts?: Preview.Counts | undefined;
        items?: Preview.Items | undefined;
    }

    export namespace Preview {
        export interface Counts {
            rules?: number | undefined;
            flows?: number | undefined;
            contexts?: number | undefined;
            values?: number | undefined;
        }

        export interface Items {
            rules?: Items.Rules.Item[] | undefined;
            flows?: Items.Flows.Item[] | undefined;
            contexts?: Items.Contexts.Item[] | undefined;
            values?: Items.Values.Item[] | undefined;
        }

        export namespace Items {
            export type Rules = Rules.Item[];

            export namespace Rules {
                export interface Item {
                    id?: string | undefined;
                    name?: string | undefined;
                    slug?: string | undefined;
                }
            }

            export type Flows = Flows.Item[];

            export namespace Flows {
                export interface Item {
                    id?: string | undefined;
                    name?: string | undefined;
                    slug?: string | undefined;
                }
            }

            export type Contexts = Contexts.Item[];

            export namespace Contexts {
                export interface Item {
                    id?: string | undefined;
                    name?: string | undefined;
                    slug?: string | undefined;
                }
            }

            export type Values = Values.Item[];

            export namespace Values {
                export interface Item {
                    id?: string | undefined;
                    name?: string | undefined;
                }
            }
        }
    }
}
