// This file was auto-generated by Fern from our API Definition.

export interface ExportManifestResponse {
    /** Manifest format version. */
    version?: string;
    exported_at?: string;
    rules?: Record<string, unknown>[];
    flows?: Record<string, unknown>[];
    contexts?: Record<string, unknown>[];
    values?: Record<string, unknown>[];
}
