/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rulebricks from "../index";

export interface FlowDetail extends Rulebricks.FlowBase {
    /** Whether the flow is published. */
    published?: boolean;
    /** The date this flow was last updated. */
    updatedAt?: Date;
}
