// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Rulebricks Flow Schema definition accepted by /admin/flows/import. If `id` is provided the matching flow is updated; otherwise a new flow is created. The server expands this into the full flow graph and (unless `_publish` is false) publishes it so it is immediately executable.
 */
export interface FlowImportPayload {
    /** Flow name. */
    name: string;
    /** Optional flow description. */
    description?: (string | null) | undefined;
    labels?: Rulebricks.AssetLabels | undefined;
    /** The flow's nodes. Exactly one must be an `origin`. */
    nodes: Rulebricks.RulebricksFlowNode[];
    /** Property and control connections between node refs. */
    connections?: Rulebricks.RulebricksFlowConnection[] | undefined;
    /** Whether to publish the flow on import (default true). Set false to import as a draft. */
    _publish?: boolean | undefined;
    /** Provide an existing flow UUID to update it instead of creating a new flow. */
    id?: string | undefined;
    /** Stable ID used for import round-tripping. */
    stable_id?: string | undefined;
    /** Optional slug (auto-generated when omitted). */
    slug?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
