// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface FlowDetail extends Rulebricks.FlowBase {
    /** Whether the flow is published. */
    published?: boolean;
    /** The date this flow was last updated. */
    updated_at?: string;
}
