// This file was auto-generated by Fern from our API Definition.

export interface Folder {
    /** Unique identifier for the folder. */
    id?: string;
    /** Name of the folder. */
    name?: string;
    /** Description of the folder. */
    description?: string;
    /** Timestamp of when the folder was last updated. */
    updated_at?: string;
}
