// This file was auto-generated by Fern from our API Definition.

export interface ImportManifestResponse {
    /** Success message. */
    message?: string;
    /** Count of imported assets by type. */
    imported?: ImportManifestResponse.Imported;
    /** Count of skipped assets by type (already exist and overwrite=false). */
    skipped?: ImportManifestResponse.Skipped;
    /** Any errors encountered during import. */
    errors?: ImportManifestResponse.Errors.Item[];
}

export namespace ImportManifestResponse {
    /**
     * Count of imported assets by type.
     */
    export interface Imported {
        rules?: number;
        flows?: number;
        contexts?: number;
        values?: number;
    }

    /**
     * Count of skipped assets by type (already exist and overwrite=false).
     */
    export interface Skipped {
        rules?: number;
        flows?: number;
        contexts?: number;
        values?: number;
    }

    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            type?: string;
            id?: string;
            error?: string;
        }
    }
}
