// This file was auto-generated by Fern from our API Definition.

export interface ImportManifestResponse {
    /** Whether the import completed successfully. */
    success?: boolean;
    /** Assets that were created during import. */
    created?: ImportManifestResponse.Created.Item[];
    /** Assets that were updated during import. */
    updated?: ImportManifestResponse.Updated.Item[];
    /** Assets that were skipped during import. */
    skipped?: ImportManifestResponse.Skipped.Item[];
    /** Any errors encountered during import. */
    errors?: ImportManifestResponse.Errors.Item[];
    /** Non-fatal warnings from import validation. */
    warnings?: string[];
    /** IDs of any organizational folders created during import. */
    organization_created?: ImportManifestResponse.OrganizationCreated | null;
}

export namespace ImportManifestResponse {
    export type Created = Created.Item[];

    export namespace Created {
        export interface Item {
            /** Asset type (context, value, rule, flow, relationship). */
            type?: string;
            /** Stable ID of asset. */
            stable_id?: string;
            /** Database ID of asset. */
            db_id?: string;
            /** Import status. */
            status?: string;
        }
    }

    export type Updated = Updated.Item[];

    export namespace Updated {
        export interface Item {
            type?: string;
            stable_id?: string;
            db_id?: string;
            status?: string;
        }
    }

    export type Skipped = Skipped.Item[];

    export namespace Skipped {
        export interface Item {
            type?: string;
            stable_id?: string;
            status?: string;
            reason?: string;
        }
    }

    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            type?: string;
            stable_id?: string;
            status?: string;
            reason?: string;
        }
    }

    /**
     * IDs of any organizational folders created during import.
     */
    export interface OrganizationCreated {
        entity_set_id?: string | null;
        rule_tag_id?: string | null;
        flow_tag_id?: string | null;
    }
}
