// This file was auto-generated by Fern from our API Definition.

export interface ImportManifestResponse {
    /** Whether the import completed successfully. */
    success?: boolean | undefined;
    /** Assets that were created during import. */
    created?: ImportManifestResponse.Created.Item[] | undefined;
    /** Assets that were updated during import. */
    updated?: ImportManifestResponse.Updated.Item[] | undefined;
    /** Assets that were skipped during import. Object-managed values are listed here with a reason such as 'Collection is managed by a workspace object' or 'Value is managed by a workspace object'; they do not cause a whole-import 409. */
    skipped?: ImportManifestResponse.Skipped.Item[] | undefined;
    /** Any errors encountered during import. */
    errors?: ImportManifestResponse.Errors.Item[] | undefined;
    /** Non-fatal warnings from import validation. */
    warnings?: string[] | undefined;
    /** IDs of any organizational folders created during import. */
    organization_created?: (ImportManifestResponse.OrganizationCreated | null) | undefined;
}

export namespace ImportManifestResponse {
    export type Created = Created.Item[];

    export namespace Created {
        export interface Item {
            /** Asset type (context, value, rule, flow, relationship). */
            type?: string | undefined;
            /** Stable ID of asset. */
            stable_id?: string | undefined;
            /** Database ID of asset. */
            db_id?: string | undefined;
            /** Import status. */
            status?: string | undefined;
        }
    }

    export type Updated = Updated.Item[];

    export namespace Updated {
        export interface Item {
            type?: string | undefined;
            stable_id?: string | undefined;
            db_id?: string | undefined;
            status?: string | undefined;
        }
    }

    export type Skipped = Skipped.Item[];

    export namespace Skipped {
        export interface Item {
            type?: string | undefined;
            stable_id?: string | undefined;
            status?: string | undefined;
            reason?: string | undefined;
        }
    }

    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            type?: string | undefined;
            stable_id?: string | undefined;
            status?: string | undefined;
            reason?: string | undefined;
        }
    }

    /**
     * IDs of any organizational folders created during import.
     */
    export interface OrganizationCreated {
        entity_set_id?: (string | null) | undefined;
        rule_tag_id?: (string | null) | undefined;
        flow_tag_id?: (string | null) | undefined;
    }
}
