/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rulebricks from "../index";

export interface ListValue extends Rulebricks.DynamicValueBase {
    /** The list value */
    value?: Rulebricks.ListValueValueItem[];
}
