// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * A rule or flow entry in an RBM manifest. The full asset document is preserved for round-trip compatibility.
 */
export interface ManifestLabeledAsset {
    data?: ManifestLabeledAsset.Data | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace ManifestLabeledAsset {
    export interface Data {
        labels?: Rulebricks.AssetLabels | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
