/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RulebricksApi from "../index";

export interface NumberValue extends RulebricksApi.DynamicValueBase {
    /** The numeric value */
    value?: number;
}
