// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface ObjectUpsertConflictResponse {
    /** Conflict message. */
    error: string;
    /** Values the object would generate but cannot adopt or overwrite. Present for value-name collisions and omitted for conflicts without colliding values. */
    collisions?: Rulebricks.ObjectValueCollision[] | undefined;
}
