// This file was auto-generated by Fern from our API Definition.

/**
 * Reported in a parallel-solve response slot when an individual rule or flow could not be executed. The reserved `$error` key cannot collide with a rule/flow's own output fields.
 */
export interface ParallelSolveEntityError {
    /** Details of the per-entity failure. */
    $error: ParallelSolveEntityError.Error_;
}

export namespace ParallelSolveEntityError {
    /**
     * Details of the per-entity failure.
     */
    export interface Error_ {
        /** Human-readable description of why this entry failed. */
        message: string;
        /** HTTP-equivalent status code of the underlying failure (e.g. 404 when the rule/flow was not found, 500 for an internal evaluation error). */
        status: number;
    }
}
