// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Response from parallel rule/flow execution with results from each execution.
 */
export type ParallelSolveResponse = Record<string, Rulebricks.DynamicResponsePayload>;
