// This file was auto-generated by Fern from our API Definition.

/**
 * A request containing multiple rule/flow executions to be run in parallel.
 */
export type ParallelSolveRequest = Record<string, ParallelSolveRequest.Value>;

export namespace ParallelSolveRequest {
    export interface Value {
        /** Slug of the rule to execute */
        $rule?: string;
        /** Slug of the flow to execute */
        $flow?: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
