/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ParallelSolveRequestValue {
    /** Slug of the rule to execute */
    rule?: string;
    /** Slug of the flow to execute */
    flow?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
