/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RulebricksApi from "../index";
/**
 * A request containing multiple rule/flow executions to be run in parallel.
 */
export type ParallelSolveRequest = Record<string, RulebricksApi.ParallelSolveRequestValue>;
