// This file was auto-generated by Fern from our API Definition.

/**
 * A response cell in a condition row.
 */
export interface RuleImportResponseCell {
    value?: unknown;
    /** Accepts any additional properties */
    [key: string]: any;
}
