// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * A single rule row containing request conditions and response output.
 */
export interface RuleImportConditionRow {
    /** Request-side cells keyed by request schema field key. */
    request: Record<string, Rulebricks.RuleImportRequestCell>;
    /** Response-side cells keyed by response schema field key. */
    response: Record<string, Rulebricks.RuleImportResponseCell>;
    settings: Rulebricks.RuleImportRowSettings;
}
