/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RulebricksApi from "../index";
export interface RuleDetail extends RulebricksApi.RuleBase {
    /** The date this rule was created. */
    createdAt?: Date;
    folder?: RulebricksApi.Folder;
    /** The published request schema for the rule. */
    requestSchema?: RulebricksApi.SchemaField[];
    /** The published response schema for the rule. */
    responseSchema?: RulebricksApi.SchemaField[];
}
