// This file was auto-generated by Fern from our API Definition.

/**
 * A request or response schema field used when importing a rule.
 */
export interface RuleImportSchemaField {
    /** Unique key for this field. */
    key: string;
    /** Whether this field is shown in the editor table. */
    show: boolean;
    /** Display name for this field. */
    name: string;
    /** Optional field description. */
    description?: string;
    /** Data type for this field. */
    type: RuleImportSchemaField.Type;
    /** Optional default value for this field. */
    defaultValue?: unknown | null;
    /** When true, this field should only accept values from a value collection. */
    valuesOnly?: boolean;
    /** Prefix used to scope available dynamic values for this field. */
    valuesPrefix?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace RuleImportSchemaField {
    /** Data type for this field. */
    export const Type = {
        String: "string",
        Number: "number",
        Boolean: "boolean",
        Date: "date",
        List: "list",
        Object: "object",
        Function: "function",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
