// This file was auto-generated by Fern from our API Definition.

export interface RuleUsage {
    /** The unique identifier for the rule. */
    id?: string;
    /** The name of the rule. */
    name?: string;
    /** The description of the rule. */
    description?: string;
    /** The unique slug for the rule used in API requests. */
    slug?: string;
    /** Whether the rule is published. */
    published?: boolean;
    /** The date this rule was last updated. */
    updated_at?: string;
}
