// This file was auto-generated by Fern from our API Definition.

/**
 * A single node in a Rulebricks Flow. `ref` is a flow-local id used only to wire `connections`; `type` selects the node kind. All other properties are that node type's config and unknown keys are preserved. Rule/origin request and response keys are defined by the referenced rule and validated server-side, so connection `output`/`input` keys are accepted as free-form strings.
 *
 * Node types:
 * - **Flow Input** - `type: origin` (aliases: `input`, `flow_input`). Input: no data input. requires a published rule.
 *   - Config: `rule`, `version`, `name`
 *   - Example: `{"ref":"origin","type":"origin","rule":"customer-eligibility"}`
 * - **Rule** - `type: rule`. Input: per-key input (each connection sets `input`). requires a published rule; gateable by Continue If.
 *   - Config: `rule`, `version`, `name`
 *   - Example: `{"ref":"rule","type":"rule","rule":"risk-score","version":"2"}`
 * - **Run Flow** - `type: flow` (aliases: `subflow`, `run_flow`). Input: per-key input (each connection sets `input`). gateable by Continue If.
 *   - Config: `flow`, `version`, `name`, `outputs`, `useCache`, `cacheExpiration`, `cacheKey`
 *   - Example: `{"ref":"flow","type":"flow","flow":"credit-check","version":"2","outputs":[{"key":"data.approved","type":"boolean"}]}`
 * - **Continue If** - `type: ifelse` (aliases: `continue_if`, `continueif`). Input: single input (key derived from the source output). emits control edges; gateable by Continue If.
 *   - Config: `condition`
 *   - Example: `{"ref":"continue_if","type":"continue_if","condition":{"operator":"greater than","args":[700]}}`
 * - **For Each Item** - `type: foreach` (aliases: `for_each`, `foreachitem`). Input: single input (key forced to `list`). gateable by Continue If.
 *   - Config: `name`, `outputs`
 *   - Example: `{"ref":"for_each","type":"for_each","outputs":[{"key":"amount","type":"number"}]}`
 * - **Combine Items** - `type: aggregate` (aliases: `combine_items`, `combineitems`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `mode`, `aggregations`, `filters`
 *   - Example: `{"ref":"combine_items","type":"combine_items","mode":"fields","aggregations":{"amount":{"operator":"sum"}}}`
 * - **Result Object** - `type: result` (aliases: `result_object`). Input: single input (key derived from the source output). terminal; gateable by Continue If.
 *   - Config: `key`, `immediateExit`, `keyMappings`, `customExitData`
 *   - Example: `{"ref":"result","type":"result","key":"data"}`
 * - **Run Code** - `type: code` (aliases: `run_code`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `name`, `code`, `prompt`, `outputs`
 *   - Example: `{"ref":"code","type":"code","name":"Score Tier Script","code":"outputs.tier = inputs.score > 700 ? 'A' : 'B'","outputs":[{"key":"tier","type":"string"}]}`
 * - **API Request** - `type: api` (aliases: `api_request`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `url`, `method`, `headers`, `body`, `useCache`, `cacheExpiration`, `jsonPaths`, `extractPaths`, `outputs`
 *   - Example: `{"ref":"api","type":"api","url":"https://api.example.com/lookup","method":"POST","headers":{"Authorization":"Bearer <token>"},"body":{"id":1},"outputs":[{"key":"ok","type":"boolean"}]}`
 * - **Database Query** - `type: db` (aliases: `database_query`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `connectionString`, `query`, `useCache`, `cacheExpiration`, `outputs`
 *   - Example: `{"ref":"db","type":"db","connectionString":"postgres://user:pass@host:5432/db","query":"SELECT score FROM customers WHERE id = $1","outputs":[{"key":"score","type":"number"}]}`
 * - **SOAP Request** - `type: soap` (aliases: `soap_request`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `wsdlUrl`, `outputs`
 *   - Example: `{"ref":"soap","type":"soap","wsdlUrl":"https://example.com/service?wsdl","outputs":[{"key":"result","type":"object"}]}`
 * - **AI Inference** - `type: ai` (aliases: `ai_inference`). Input: single input (key derived from the source output). gateable by Continue If.
 *   - Config: `model`, `labels`
 *   - Example: `{"ref":"ai","type":"ai","labels":[{"name":"Sentiment","type":"string","description":"Overall sentiment"}]}`
 * - **Lookup Table** - `type: lookup` (aliases: `lookup_table`). Input: single input (key forced to `lookup`). gateable by Continue If.
 *   - Config: `table`, `keyType`, `valueType`, `defaultValue`
 *   - Example: `{"ref":"lookup","type":"lookup","table":[{"key":"gold","value":0.2},{"key":"silver","value":0.1}],"keyType":"string","valueType":"number","defaultValue":0}`
 * - **Vault** - `type: vault`. Input: no data input.
 *   - Config: `provider`, `credentials`, `secrets`
 *   - Example: `{"ref":"vault","type":"vault","secrets":[{"name":"STRIPE_API_KEY"}]}`
 * - **Context Operation** - `type: entity` (aliases: `context_operation`). Input: per-key input (each connection sets `input`). gateable by Continue If.
 *   - Config: `operation`, `entitySlug`, `identityFieldKey`, `selectedUpdateFields`, `updateValues`, `includeRelations`, `outputs`
 *   - Example: `{"ref":"entity","type":"entity","operation":"read","entitySlug":"customer"}`
 * - **Send Notification** - `type: notification` (aliases: `send_notification`). Input: single input (key derived from the source output). terminal; gateable by Continue If.
 *   - Config: `channels`, `titleTemplate`, `messageTemplate`
 *   - Example: `{"ref":"notification","type":"notification","channels":{"email":{"enabled":true,"addresses":["alerts@example.com"]}},"titleTemplate":"Flow alert","messageTemplate":"A flow reached the notification step."}`
 */
export interface RulebricksFlowNode {
    /** Unique, flow-local id used to reference this node in `connections`. */
    ref: string;
    /** Node type (a canonical key or a friendly alias). */
    type: RulebricksFlowNode.Type;
    /** Config for node types: origin, rule. A published rule slug, optionally `slug/version`. */
    rule?: string | undefined;
    /** Config for node types: origin, rule, flow. Published version to pin (e.g. "3"). Optional for rule/origin nodes (omit to use the latest published version); REQUIRED for flow nodes, which cannot target "latest". */
    version?: unknown | undefined;
    /** Config for node types: origin, rule, flow, foreach, code. Optional human-readable display name for the step (code nodes show it as the script title on the node). */
    name?: string | undefined;
    /** Config for node type: flow. A published flow slug to invoke as a subflow, optionally `slug/version`. A pinned numeric version is REQUIRED (here or via `version`), and the target flow must not (transitively) invoke this flow. */
    flow?: string | undefined;
    /** Config for node types: flow, foreach, code, api, db, soap, entity. Declared output handles - declare every output you wire to a downstream node. */
    outputs?: RulebricksFlowNode.Outputs.Item[] | undefined;
    /** Config for node types: flow, api, db. */
    useCache?: boolean | undefined;
    /** Config for node types: flow, api, db. */
    cacheExpiration?: number | undefined;
    /** Config for node type: flow. */
    cacheKey?: string | undefined;
    /** Config for node type: ifelse. Continue If gating condition; evaluated against the single wired input. */
    condition?: RulebricksFlowNode.Condition | undefined;
    /** Config for node type: aggregate. */
    mode?: RulebricksFlowNode.Mode | undefined;
    /** Config for node type: aggregate. */
    aggregations?: Record<string, RulebricksFlowNode.Aggregations.Value> | undefined;
    /** Config for node type: aggregate. */
    filters?: unknown[] | undefined;
    /** Config for node type: result. */
    key?: string | undefined;
    /** Config for node type: result. */
    immediateExit?: boolean | undefined;
    /** Config for node type: result. */
    keyMappings?: Record<string, string> | undefined;
    /** Config for node type: result. */
    customExitData?: (string | null) | undefined;
    /** Config for node type: code. JavaScript that reads `inputs.<key>` and assigns to `outputs.<key>`. */
    code?: string | undefined;
    /** Config for node type: code. */
    prompt?: string | undefined;
    /** Config for node type: api. */
    url?: string | undefined;
    /** Config for node type: api. */
    method?: string | undefined;
    /** Config for node type: api. */
    headers?: unknown | undefined;
    /** Config for node type: api. */
    body?: unknown | undefined;
    /** Config for node type: api. */
    jsonPaths?: unknown | undefined;
    /** Config for node type: api. */
    extractPaths?: boolean | undefined;
    /** Config for node type: db. */
    connectionString?: string | undefined;
    /** Config for node type: db. */
    query?: string | undefined;
    /** Config for node type: soap. */
    wsdlUrl?: string | undefined;
    /** Config for node type: ai. */
    model?: string | undefined;
    /** Config for node type: ai. */
    labels?: RulebricksFlowNode.Labels.Item[] | undefined;
    /** Config for node type: lookup. */
    table?: RulebricksFlowNode.Table.Item[] | undefined;
    /** Config for node type: lookup. */
    keyType?: string | undefined;
    /** Config for node type: lookup. */
    valueType?: string | undefined;
    /** Config for node type: lookup. */
    defaultValue?: unknown | undefined;
    /** Config for node type: vault. */
    provider?: string | undefined;
    /** Config for node type: vault. */
    credentials?: Record<string, unknown> | undefined;
    /** Config for node type: vault. */
    secrets?: RulebricksFlowNode.Secrets.Item[] | undefined;
    /** Config for node type: entity. */
    operation?: RulebricksFlowNode.Operation | undefined;
    /** Config for node type: entity. */
    entitySlug?: string | undefined;
    /** Config for node type: entity. */
    identityFieldKey?: string | undefined;
    /** Config for node type: entity. */
    selectedUpdateFields?: Record<string, boolean> | undefined;
    /** Config for node type: entity. */
    updateValues?: Record<string, unknown> | undefined;
    /** Config for node type: entity. */
    includeRelations?: Record<string, boolean> | undefined;
    /** Config for node type: notification. */
    channels?: Record<string, unknown> | undefined;
    /** Config for node type: notification. */
    titleTemplate?: string | undefined;
    /** Config for node type: notification. */
    messageTemplate?: string | undefined;
    /** Optional escape hatch: properties merged verbatim onto the expanded node.data for advanced or forward-compatible fields. */
    data?: Record<string, unknown> | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace RulebricksFlowNode {
    /** Node type (a canonical key or a friendly alias). */
    export const Type = {
        Origin: "origin",
        Input: "input",
        FlowInput: "flow_input",
        Rule: "rule",
        Flow: "flow",
        Subflow: "subflow",
        RunFlow: "run_flow",
        Ifelse: "ifelse",
        ContinueIf: "continue_if",
        Continueif: "continueif",
        Foreach: "foreach",
        ForEach: "for_each",
        Foreachitem: "foreachitem",
        Aggregate: "aggregate",
        CombineItems: "combine_items",
        Combineitems: "combineitems",
        Result: "result",
        ResultObject: "result_object",
        Code: "code",
        RunCode: "run_code",
        Api: "api",
        ApiRequest: "api_request",
        Db: "db",
        DatabaseQuery: "database_query",
        Soap: "soap",
        SoapRequest: "soap_request",
        Ai: "ai",
        AiInference: "ai_inference",
        Lookup: "lookup",
        LookupTable: "lookup_table",
        Vault: "vault",
        Entity: "entity",
        ContextOperation: "context_operation",
        Notification: "notification",
        SendNotification: "send_notification",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export type Outputs = Outputs.Item[];

    export namespace Outputs {
        export interface Item {
            key: string;
            type?: Item.Type | undefined;
            name?: string | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export namespace Item {
            export const Type = {
                String: "string",
                Number: "number",
                Boolean: "boolean",
                List: "list",
                Object: "object",
                Date: "date",
                Any: "any",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }

    /**
     * Config for node type: ifelse. Continue If gating condition; evaluated against the single wired input.
     */
    export interface Condition {
        property?: string | undefined;
        operator?: string | undefined;
        args?: unknown[] | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    /** Config for node type: aggregate. */
    export const Mode = {
        Fields: "fields",
        Items: "items",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];

    export namespace Aggregations {
        export interface Value {
            operator?: string | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }
    }

    export type Labels = Labels.Item[];

    export namespace Labels {
        export interface Item {
            name: string;
            type?: Item.Type | undefined;
            description?: string | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export namespace Item {
            export const Type = {
                String: "string",
                Number: "number",
                Boolean: "boolean",
                List: "list",
                Object: "object",
                Date: "date",
                Any: "any",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }

    export type Table = Table.Item[];

    export namespace Table {
        export interface Item {
            key?: unknown | undefined;
            value?: unknown | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }
    }

    export type Secrets = Secrets.Item[];

    export namespace Secrets {
        export interface Item {
            name: string;
            /** Accepts any additional properties */
            [key: string]: any;
        }
    }

    /** Config for node type: entity. */
    export const Operation = {
        Read: "read",
        Update: "update",
        Delete: "delete",
        BatchUpdate: "batch_update",
    } as const;
    export type Operation = (typeof Operation)[keyof typeof Operation];
}
