// This file was auto-generated by Fern from our API Definition.

export interface RunTestsRequest {
    /** When true, run only the tests flagged as critical (a smoke test). Defaults to false (run the entire suite). */
    critical_only?: boolean | undefined;
}
