// This file was auto-generated by Fern from our API Definition.

/**
 * Solver fleet warm-up status (self-hosted deployments). Poll GET /scale until `status` is `ready` before starting a large batch workload.
 */
export interface ScaleStatusResponse {
    /** `idle`: no warm-up is active. `scaling`: a warm-up is active and workers are still joining. `ready`: the active worker count reached the target. */
    status: ScaleStatusResponse.Status;
    /** Solvers currently joined to the processing group and able to accept work. Null when the deployment runs without a message broker (no autoscaling). */
    active_workers?: (number | null) | undefined;
    /** The fleet ceiling a warm-up scales toward - a function of the deployment's configuration, never caller input. */
    target_workers: number;
    /** Seconds until the active warm-up lapses and normal autoscaling reclaims the capacity. 0 when idle. Repeat POST /scale calls refresh the window. */
    expires_in_seconds: number;
}

export namespace ScaleStatusResponse {
    /** `idle`: no warm-up is active. `scaling`: a warm-up is active and workers are still joining. `ready`: the active worker count reached the target. */
    export const Status = {
        Idle: "idle",
        Scaling: "scaling",
        Ready: "ready",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
