/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Data type of this field.
 */
export type SchemaFieldType = "string" | "number" | "boolean" | "object" | "array";
export const SchemaFieldType = {
    String: "string",
    Number: "number",
    Boolean: "boolean",
    Object: "object",
    Array: "array",
} as const;
