/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Data type of this field.
 */
export type SchemaFieldType = "string" | "number" | "boolean" | "object" | "array";
export declare const SchemaFieldType: {
    readonly String: "string";
    readonly Number: "number";
    readonly Boolean: "boolean";
    readonly Object: "object";
    readonly Array: "array";
};
