// This file was auto-generated by Fern from our API Definition.

export interface SchemaField {
    /** The unique key for this field. */
    key?: string;
    /** Whether this field is visible in the UI. */
    show?: boolean;
    /** Display name for this field. */
    name?: string;
    /** Description of this field. */
    description?: string;
    /** Data type of this field. */
    type?: SchemaField.Type;
    /** Default value for this field. */
    defaultValue?: SchemaField.DefaultValue | null;
    /** Computed default value for this field. */
    defaultComputedValue?: string | null;
    /** Transformation expression to apply to this field. */
    transform?: string;
}

export namespace SchemaField {
    /** Data type of this field. */
    export const Type = {
        String: "string",
        Number: "number",
        Boolean: "boolean",
        Object: "object",
        Array: "array",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /**
     * Default value for this field.
     */
    export type DefaultValue = string | number | boolean | Record<string, unknown> | unknown[];
}
