// This file was auto-generated by Fern from our API Definition.

/**
 * Optional request body for executing a flow against context. The entire body is merged with instance state before flow execution.
 */
export type SolveContextFlowRequest = Record<string, unknown>;
