// This file was auto-generated by Fern from our API Definition.

/**
 * Response after executing a flow against a context instance.
 */
export interface SolveContextFlowResponse {
    /** Whether the flow executed successfully. */
    status?: SolveContextFlowResponse.Status | undefined;
    /** Combined identifier in format 'contextSlug:instanceId'. */
    context?: string | undefined;
    /** The slug of the flow that was executed. */
    flow?: string | undefined;
    /** The flow execution output. */
    result?: Record<string, unknown> | undefined;
    /** Resource usage information for the flow execution. */
    usage?: Record<string, unknown> | undefined;
}

export namespace SolveContextFlowResponse {
    /** Whether the flow executed successfully. */
    export const Status = {
        Solved: "solved",
        Error: "error",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
