/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rulebricks from "../index";

export interface StringValue extends Rulebricks.DynamicValueBase {
    /** The string value */
    value?: string;
}
