// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

/**
 * Response after submitting data, including any auto-executed evaluations.
 */
export interface SubmitContextDataResponse {
    /** Combined identifier in format 'contextSlug:instanceId'. */
    context?: string | undefined;
    /** The merged state after submitting data and any auto-executed rules/flows. */
    state?: Record<string, unknown> | undefined;
    /** Whether all required fields are present ('complete') or some are missing ('pending'). */
    status?: SubmitContextDataResponse.Status | undefined;
    /** List of field keys that are currently populated. */
    have?: string[] | undefined;
    /** List of required field keys that are still missing. */
    need?: string[] | undefined;
    /** Whether this submission created a new instance (true) or updated an existing one (false). */
    is_new?: boolean | undefined;
    /** When the instance will expire based on context TTL. */
    expires_at?: (string | null) | undefined;
    /** Results from auto-executed rules/flows and pending evaluation cascades. */
    cascaded?: Rulebricks.CascadeResult[] | undefined;
}

export namespace SubmitContextDataResponse {
    /** Whether all required fields are present ('complete') or some are missing ('pending'). */
    export const Status = {
        Complete: "complete",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
