// This file was auto-generated by Fern from our API Definition.

export interface Test {
    /** Unique identifier for the test. */
    id: string;
    /** The name of the test. */
    name: string;
    /** The request object for the test. */
    request: Record<string, unknown>;
    /** The expected response object for the test. */
    response: Record<string, unknown>;
    /** Indicates whether the test is critical. */
    critical: boolean;
    /** Indicates if the test resulted in an error. Null if test has not been executed. */
    error?: (boolean | null) | undefined;
    /** Indicates if the test was successful. Null if test has not been executed. */
    success?: (boolean | null) | undefined;
    /** The state of the test after execution. */
    test_state?: (Test.TestState | null) | undefined;
    /** The timestamp when the test was last executed. */
    last_executed?: (string | null) | undefined;
}

export namespace Test {
    /**
     * The state of the test after execution.
     */
    export interface TestState {
        /** Execution time in seconds */
        duration?: number | undefined;
        /** Actual response returned */
        response?: (Record<string, unknown> | null) | undefined;
        conditions?: Record<string, unknown>[] | undefined;
        /** HTTP status code returned */
        http_status?: number | undefined;
        success_idxs?: number[] | undefined;
        /** Error message or flag indicating if evaluation error occurred */
        evaluation_error?: TestState.EvaluationError | undefined;
    }

    export namespace TestState {
        /**
         * Error message or flag indicating if evaluation error occurred
         */
        export type EvaluationError = boolean | string;
    }
}
