/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error message or flag indicating if evaluation error occurred
 */
export type TestTestStateEvaluationError = boolean | string;
