// This file was auto-generated by Fern from our API Definition.

/**
 * Summary counts returned by value writes when the workspace catalog is too large to echo back in full.
 */
export interface UpdateValuesSummaryResponse {
    /** Number of new values created in this call. */
    created?: number | undefined;
    /** Number of existing values updated in this call. */
    updated?: number | undefined;
    /** Total number of values processed in this call. */
    processed?: number | undefined;
}
