// This file was auto-generated by Fern from our API Definition.

/**
 * Response after updating a context.
 */
export interface UpdateContextResponse {
    /** The unique identifier of the updated context. */
    id?: string;
    /** The slug of the updated context. */
    slug?: string;
    /** The name of the updated context. */
    name?: string;
    /** Timestamp of when the context was updated. */
    updated_at?: string;
}
