// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../index.js";

export interface UpsertObjectResponse {
    /** True when the object was created by this call. */
    created?: boolean | undefined;
    object?: Rulebricks.WorkspaceObject | undefined;
    /** Managed-value sync results (or would_sync / would_archive for dry runs). */
    values?: UpsertObjectResponse.Values | undefined;
}

export namespace UpsertObjectResponse {
    /**
     * Managed-value sync results (or would_sync / would_archive for dry runs).
     */
    export interface Values {
        /** Managed values created or updated. */
        synced?: number | undefined;
        /** Previously generated values archived because the schema no longer declares them. */
        archived?: number | undefined;
        /** Dry run: managed values that would be synced. */
        would_sync?: number | undefined;
        /** Dry run: values that would be archived. */
        would_archive?: Values.WouldArchive.Item[] | undefined;
    }

    export namespace Values {
        export type WouldArchive = WouldArchive.Item[];

        export namespace WouldArchive {
            export interface Item {
                id?: string | undefined;
                name?: string | undefined;
            }
        }
    }
}
