// This file was auto-generated by Fern from our API Definition.

export interface UsageStatistics {
    /** The current plan of the organization. */
    plan?: string;
    /** The start date of the current monthly period. */
    monthly_period_start?: string;
    /** The end date of the current monthly period. */
    monthly_period_end?: string;
    /** The number of rule executions used this month. */
    monthly_executions_usage?: number;
    /** The total number of rule executions allowed this month. */
    monthly_executions_limit?: number;
    /** The number of rule executions remaining this month. */
    monthly_executions_remaining?: number;
}
