// This file was auto-generated by Fern from our API Definition.

export interface UserInviteResponse {
    /** Success message indicating whether a new user was invited or an existing user's permissions were updated. */
    message?: string | undefined;
    user?: UserInviteResponse.User | undefined;
}

export namespace UserInviteResponse {
    export interface User {
        /** Email of the invited user. */
        email?: string | undefined;
        /** Role assigned to the user. */
        role?: string | undefined;
        /** User groups assigned to the user. */
        user_groups?: string[] | undefined;
    }
}
