// This file was auto-generated by Fern from our API Definition.

export interface UserInviteResponse {
    /** Success message indicating whether a new user was invited or an existing user's permissions were updated. */
    message?: string;
    user?: UserInviteResponse.User;
}

export namespace UserInviteResponse {
    export interface User {
        /** Email of the invited user. */
        email?: string;
        /** Role assigned to the user. */
        role?: string;
        /** Access groups assigned to the user. */
        accessGroups?: string[];
    }
}
