// This file was auto-generated by Fern from our API Definition.

/**
 * Detailed information about a user in the organization.
 */
export interface UserDetail {
    /** Unique identifier for the user. */
    id?: string;
    /** Email address of the user. */
    email?: string;
    /** Display name of the user (if set). */
    name?: string | null;
    /** API key assigned to the user. */
    apiKey?: string | null;
    /** Role assigned to the user (e.g., 'administrator', 'developer', 'editor', or custom role ID). */
    role?: string;
    /** List of access group names the user belongs to. */
    accessGroups?: string[];
    /** Date and time when the user joined the organization. */
    joinedAt?: string | null;
}
