// This file was auto-generated by Fern from our API Definition.

export interface UserGroup {
    /** Unique identifier of the user group. */
    id?: string | undefined;
    /** Name of the user group. */
    name?: string | undefined;
    /** Description of the user group. */
    description?: string | undefined;
    /** When the user group was created. */
    created_at?: string | undefined;
}
