// This file was auto-generated by Fern from our API Definition.

/**
 * A value-to-value reference marker. On writes, reference a value by name with { "$ref": "<value name>" } or by ID with { "$rb": "globalValue", "id": "<value id>" }. Name references are resolved and stored as ID references, so renames never break them. A scalar payload may be a single reference; list payloads may mix literal items and references. Reads with resolve=false return the stored id-based markers.
 */
export interface ValueReference {
    /** Full name of the referenced value (write-time form), e.g. 'Medical Codes.A123'. */
    $ref?: string | undefined;
    /** Marker discriminator for id-based references. */
    $rb?: ValueReference.Rb | undefined;
    /** Id of the referenced value (stored form). */
    id?: string | undefined;
    /** Denormalized display name of the referenced value (stored form; may lag renames). */
    name?: string | undefined;
}

export namespace ValueReference {
    /** Marker discriminator for id-based references. */
    export const Rb = {
        GlobalValue: "globalValue",
    } as const;
    export type Rb = (typeof Rb)[keyof typeof Rb];
}
