/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * System limits for dynamic values
 */
export interface ValueLimits {
    /** Maximum number of value keys per user */
    maxKeys?: number;
    /** Maximum length of a single value in characters */
    maxValueLength?: number;
    /** Maximum total size of all values in bytes */
    maxTotalSize?: number;
    /** Maximum length of a key name */
    maxKeyLength?: number;
}
