// This file was auto-generated by Fern from our API Definition.

/**
 * System limits for vocabulary values
 */
export interface ValueLimits {
    /** Maximum number of vocabulary values per workspace (a guardrail against runaway imports; the system is designed to operate at this scale) */
    MAX_KEYS?: number | undefined;
    /** Maximum serialized length of a single value payload in characters */
    MAX_VALUE_LENGTH?: number | undefined;
    /** Maximum length of a value name in characters, including collection prefixes */
    MAX_KEY_LENGTH?: number | undefined;
}
