// This file was auto-generated by Fern from our API Definition.

/**
 * System limits for dynamic values
 */
export interface ValueLimits {
    /** Maximum number of value keys per user */
    MAX_KEYS?: number;
    /** Maximum length of a single value in characters */
    MAX_VALUE_LENGTH?: number;
    /** Maximum total size of all values in bytes */
    MAX_TOTAL_SIZE?: number;
    /** Maximum length of a key name */
    MAX_KEY_LENGTH?: number;
}
