"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListDynamicValuesResponseItemType = void 0;
exports.ListDynamicValuesResponseItemType = {
    String: "string",
    Number: "number",
    Boolean: "boolean",
    List: "list",
};
