/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Data type of the dynamic value.
 */
export declare type ListDynamicValuesResponseItemType = "string" | "number" | "boolean" | "list";
export declare const ListDynamicValuesResponseItemType: {
    readonly String: "string";
    readonly Number: "number";
    readonly Boolean: "boolean";
    readonly List: "list";
};
