// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../index.js";

export type UpdateValuesResponse = Rulebricks.DynamicValueListResponse | Rulebricks.UpdateValuesSummaryResponse;
