// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface ListRulesRequest {
    /** The unique identifier for the resource. */
    slug: string;
}
