/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as RulebricksApi from "../../../../api";
import * as core from "../../../../core";
export declare const ListRuleTestsResponseItem: core.serialization.ObjectSchema<serializers.ListRuleTestsResponseItem.Raw, RulebricksApi.ListRuleTestsResponseItem>;
export declare namespace ListRuleTestsResponseItem {
    interface Raw {
        id: string;
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
        error: boolean;
        success: boolean;
        testState?: Record<string, unknown> | null;
        lastExecuted?: string | null;
    }
}
