// This file was auto-generated by Fern from our API Definition.

import type * as Rulebricks from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *         name: "Updated Customer",
 *         description: "Updated description for premium customers"
 *     }
 */
export interface UpdateContextRequest {
    /** The unique identifier for the context. */
    id: string;
    /** The name of the context. Changing it regenerates the context's slug. */
    name?: string;
    /** The description of the context. */
    description?: string;
    /** Updated schema for the context: an object with `base` and optional `derived` field arrays. */
    schema?: Rulebricks.ContextSchema;
    /** The fact key to use as the unique identifier for instances. Must be a key from schema.base. Caution: changing this on a context with live instances changes how future writes resolve instances. */
    identity_fact?: string;
    /** When true, bound rules and flows automatically execute when their inputs are satisfied. */
    auto_execute_decisions?: boolean;
    /** Time-to-live in seconds for live context instances (60 seconds to 30 days). Instances expire after this duration. */
    ttl_seconds?: number;
    /** Maximum number of history entries to retain per field. */
    history_limit?: number;
    /** How to handle submitted fields that don't match the schema: `ignore` drops them, `reject` fails the request (or the batch item), `store` persists them alongside declared facts. */
    on_schema_mismatch?: UpdateContextRequest.OnSchemaMismatch;
}

export namespace UpdateContextRequest {
    /** How to handle submitted fields that don't match the schema: `ignore` drops them, `reject` fails the request (or the batch item), `store` persists them alongside declared facts. */
    export const OnSchemaMismatch = {
        Ignore: "ignore",
        Reject: "reject",
        Store: "store",
    } as const;
    export type OnSchemaMismatch = (typeof OnSchemaMismatch)[keyof typeof OnSchemaMismatch];
}
