/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteDynamicValueRequest {
    /**
     * ID of the dynamic value to delete
     */
    id: string;
}
