// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         collection: "Medical Codes",
 *         values: {
 *             "A123": "A123",
 *             "B456": "B456",
 *             "C789": "C789"
 *         }
 *     }
 *
 * @example
 *     {
 *         collection: "Medical Codes",
 *         values: {
 *             "Y998": "Y998",
 *             "Z999": "Z999"
 *         },
 *         sync_id: "fabric-2026-08-13T02:00Z",
 *         complete: true
 *     }
 */
export interface SyncValuesRequest {
    /** Collection path to sync (e.g. 'Medical Codes'). Only values under this path are affected. */
    collection: string;
    /** Desired members of the collection, keyed relative to the collection path ('A123' becomes 'Medical Codes.A123'). Nested objects flatten with dot notation, and payloads may use ValueReference markers. An empty object empties the collection. May be omitted on a pure finalize call (sync_id + complete). */
    values?: Record<string, unknown>;
    /** Identifier for a chunked run. Repeat the call with the same sync_id for each chunk of the desired state; nothing is removed until a call with complete: true. Abandoned runs are purged after 24 hours without removing anything. */
    sync_id?: string;
    /** Marks the run as complete, triggering the removal sweep. Implicitly true when sync_id is omitted (single-request syncs), false otherwise. */
    complete?: boolean;
    /** Hard-delete removed values instead of archiving them. Removals still referenced by a rule, flow, or surviving value are archived instead and reported in 'blocked'. Self-hosted deployments retain tombstones regardless. */
    permanently_delete?: boolean;
    /** Compute and return the full diff without writing anything. Only supported for single-request syncs (omit sync_id). */
    dry_run?: boolean;
    /** Optional array of user group names to assign to written values, matching POST /values. */
    user_groups?: string[];
    /** Optional metadata keyed by FULL value name (including the collection prefix). */
    metadata_by_name?: Record<string, Record<string, unknown>>;
}
