/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const BulkRuleResponseItemError: core.serialization.ObjectSchema<
    serializers.BulkRuleResponseItemError.Raw,
    RulebricksApi.BulkRuleResponseItemError
> = core.serialization.object({
    error: core.serialization.string().optional(),
});

export declare namespace BulkRuleResponseItemError {
    export interface Raw {
        error?: string | null;
    }
}
