/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const BulkRuleResponseItemError: core.serialization.ObjectSchema<serializers.BulkRuleResponseItemError.Raw, RulebricksApi.BulkRuleResponseItemError>;
export declare namespace BulkRuleResponseItemError {
    interface Raw {
        error?: string | null;
    }
}
