/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const CreateTestRequest: core.serialization.ObjectSchema<
    serializers.CreateTestRequest.Raw,
    RulebricksApi.CreateTestRequest
> = core.serialization.object({
    name: core.serialization.string(),
    request: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    response: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    critical: core.serialization.boolean(),
});

export declare namespace CreateTestRequest {
    export interface Raw {
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
    }
}
