/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const DecisionLogRequest: core.serialization.ObjectSchema<serializers.DecisionLogRequest.Raw, RulebricksApi.DecisionLogRequest>;
export declare namespace DecisionLogRequest {
    interface Raw {
        ip?: string | null;
        method?: string | null;
        name?: string | null;
        endpoint?: string | null;
        params?: Record<string, string[]> | null;
        data?: unknown | null;
    }
}
