/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { DecisionLog } from "./DecisionLog";

export const DecisionLogResponse: core.serialization.ObjectSchema<
    serializers.DecisionLogResponse.Raw,
    Rulebricks.DecisionLogResponse
> = core.serialization.object({
    data: core.serialization.list(DecisionLog).optional(),
    cursor: core.serialization.string().optional(),
});

export declare namespace DecisionLogResponse {
    export interface Raw {
        data?: DecisionLog.Raw[] | null;
        cursor?: string | null;
    }
}
