/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { DecisionLogDecisionConditionsItemValue } from "./DecisionLogDecisionConditionsItemValue";
export declare const DecisionLogDecision: core.serialization.ObjectSchema<serializers.DecisionLogDecision.Raw, RulebricksApi.DecisionLogDecision>;
export declare namespace DecisionLogDecision {
    interface Raw {
        conditions?: Record<string, DecisionLogDecisionConditionsItemValue.Raw>[] | null;
        successIdxs?: number[] | null;
    }
}
