/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";

export const DecisionLog: core.serialization.Schema<serializers.DecisionLog.Raw, Rulebricks.DecisionLog> =
    core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DecisionLog {
    export type Raw = Record<string, unknown>;
}
