/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const DecisionLogDecisionConditionsItemValue: core.serialization.ObjectSchema<serializers.DecisionLogDecisionConditionsItemValue.Raw, RulebricksApi.DecisionLogDecisionConditionsItemValue>;
export declare namespace DecisionLogDecisionConditionsItemValue {
    interface Raw {
        result?: boolean | null;
        err?: string | null;
    }
}
