/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { DecisionLogRequest } from "./DecisionLogRequest";
import { DecisionLogDecision } from "./DecisionLogDecision";

export const DecisionLog: core.serialization.ObjectSchema<serializers.DecisionLog.Raw, Rulebricks.DecisionLog> =
    core.serialization.object({
        request: DecisionLogRequest.optional(),
        response: core.serialization.lazyObject(() => serializers.DecisionLogResponse).optional(),
        decision: DecisionLogDecision.optional(),
    });

export declare namespace DecisionLog {
    export interface Raw {
        request?: DecisionLogRequest.Raw | null;
        response?: serializers.DecisionLogResponse.Raw | null;
        decision?: DecisionLogDecision.Raw | null;
    }
}
