/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";

export const DynamicResponsePayload: core.serialization.Schema<
    serializers.DynamicResponsePayload.Raw,
    Rulebricks.DynamicResponsePayload
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DynamicResponsePayload {
    export type Raw = Record<string, unknown>;
}
