/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { DynamicValue } from "./DynamicValue";
export declare const DynamicValueListResponse: core.serialization.Schema<serializers.DynamicValueListResponse.Raw, RulebricksApi.DynamicValueListResponse>;
export declare namespace DynamicValueListResponse {
    type Raw = DynamicValue.Raw[];
}
