/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { RuleUsage } from "./RuleUsage";
export declare const DynamicValueBase: core.serialization.ObjectSchema<serializers.DynamicValueBase.Raw, RulebricksApi.DynamicValueBase>;
export declare namespace DynamicValueBase {
    interface Raw {
        id?: string | null;
        name?: string | null;
        usages?: RuleUsage.Raw[] | null;
        accessGroups?: string[] | null;
    }
}
