/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const DynamicResponsePayload: core.serialization.Schema<serializers.DynamicResponsePayload.Raw, RulebricksApi.DynamicResponsePayload>;
export declare namespace DynamicResponsePayload {
    type Raw = Record<string, unknown>;
}
