/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { DynamicValue } from "./DynamicValue";

export const DynamicValueListResponse: core.serialization.Schema<
    serializers.DynamicValueListResponse.Raw,
    Rulebricks.DynamicValueListResponse
> = core.serialization.list(DynamicValue);

export declare namespace DynamicValueListResponse {
    export type Raw = DynamicValue.Raw[];
}
