/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";

export const DynamicRequestPayload: core.serialization.Schema<
    serializers.DynamicRequestPayload.Raw,
    Rulebricks.DynamicRequestPayload
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DynamicRequestPayload {
    export type Raw = Record<string, unknown>;
}
