/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, RulebricksApi.Error_> =
    core.serialization.object({
        error: core.serialization.string().optional(),
    });

export declare namespace Error_ {
    export interface Raw {
        error?: string | null;
    }
}
