/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { FlowDetail } from "./FlowDetail";

export const FlowListResponse: core.serialization.Schema<
    serializers.FlowListResponse.Raw,
    RulebricksApi.FlowListResponse
> = core.serialization.list(FlowDetail);

export declare namespace FlowListResponse {
    export type Raw = FlowDetail.Raw[];
}
