/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const FlowExecutionError: core.serialization.ObjectSchema<
    serializers.FlowExecutionError.Raw,
    RulebricksApi.FlowExecutionError
> = core.serialization.object({
    error: core.serialization.string().optional(),
    node: core.serialization.string().optional(),
    details: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace FlowExecutionError {
    export interface Raw {
        error?: string | null;
        node?: string | null;
        details?: Record<string, unknown> | null;
    }
}
