/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { FlowBase } from "./FlowBase";

export const FlowDetail: core.serialization.ObjectSchema<serializers.FlowDetail.Raw, Rulebricks.FlowDetail> =
    core.serialization
        .object({
            published: core.serialization.boolean().optional(),
            updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
        })
        .extend(FlowBase);

export declare namespace FlowDetail {
    export interface Raw extends FlowBase.Raw {
        published?: boolean | null;
        updated_at?: string | null;
    }
}
