/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const FlowBase: core.serialization.ObjectSchema<serializers.FlowBase.Raw, RulebricksApi.FlowBase>;
export declare namespace FlowBase {
    interface Raw {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        slug?: string | null;
    }
}
