/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { FlowBase } from "./FlowBase";
export declare const FlowDetail: core.serialization.ObjectSchema<serializers.FlowDetail.Raw, RulebricksApi.FlowDetail>;
export declare namespace FlowDetail {
    interface Raw extends FlowBase.Raw {
        published?: boolean | null;
        updated_at?: string | null;
    }
}
