/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { Folder } from "./Folder";

export const FolderListResponse: core.serialization.Schema<
    serializers.FolderListResponse.Raw,
    Rulebricks.FolderListResponse
> = core.serialization.list(Folder);

export declare namespace FolderListResponse {
    export type Raw = Folder.Raw[];
}
