/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const Folder: core.serialization.ObjectSchema<serializers.Folder.Raw, RulebricksApi.Folder> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        updatedAt: core.serialization.date().optional(),
    });

export declare namespace Folder {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        updatedAt?: string | null;
    }
}
