/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { Folder } from "./Folder";
export declare const FolderListResponse: core.serialization.Schema<serializers.FolderListResponse.Raw, RulebricksApi.FolderListResponse>;
export declare namespace FolderListResponse {
    type Raw = Folder.Raw[];
}
