/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const Folder: core.serialization.ObjectSchema<serializers.Folder.Raw, RulebricksApi.Folder>;
export declare namespace Folder {
    interface Raw {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        updatedAt?: string | null;
    }
}
