/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RulebricksApi from "../../api";
import * as core from "../../core";
export declare const InternalServerErrorBody: core.serialization.ObjectSchema<serializers.InternalServerErrorBody.Raw, RulebricksApi.InternalServerErrorBody>;
export declare namespace InternalServerErrorBody {
    interface Raw {
        error?: string | null;
    }
}
