/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { DynamicValueBase } from "./DynamicValueBase";
export declare const ListValue: core.serialization.ObjectSchema<serializers.ListValue.Raw, RulebricksApi.ListValue>;
export declare namespace ListValue {
    interface Raw extends DynamicValueBase.Raw {
        value?: string[] | null;
    }
}
