/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { DynamicValueBase } from "./DynamicValueBase";

export const NumberValue: core.serialization.ObjectSchema<serializers.NumberValue.Raw, Rulebricks.NumberValue> =
    core.serialization
        .object({
            value: core.serialization.number().optional(),
        })
        .extend(DynamicValueBase);

export declare namespace NumberValue {
    export interface Raw extends DynamicValueBase.Raw {
        value?: number | null;
    }
}
