/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { DynamicValueBase } from "./DynamicValueBase";
export declare const NumberValue: core.serialization.ObjectSchema<serializers.NumberValue.Raw, RulebricksApi.NumberValue>;
export declare namespace NumberValue {
    interface Raw extends DynamicValueBase.Raw {
        value?: number | null;
    }
}
