/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { DynamicResponsePayload } from "./DynamicResponsePayload";
export declare const ParallelSolveResponse: core.serialization.Schema<serializers.ParallelSolveResponse.Raw, RulebricksApi.ParallelSolveResponse>;
export declare namespace ParallelSolveResponse {
    type Raw = Record<string, DynamicResponsePayload.Raw>;
}
