/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const ParallelSolveRequestValue: core.serialization.ObjectSchema<serializers.ParallelSolveRequestValue.Raw, RulebricksApi.ParallelSolveRequestValue>;
export declare namespace ParallelSolveRequestValue {
    interface Raw {
        $rule?: string | null;
        $flow?: string | null;
        [key: string]: any;
    }
}
