/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { Folder } from "./Folder";
import { SchemaField } from "./SchemaField";
import { RuleBase } from "./RuleBase";

export const RuleDetail: core.serialization.ObjectSchema<serializers.RuleDetail.Raw, RulebricksApi.RuleDetail> =
    core.serialization
        .object({
            createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
            folder: Folder.optional(),
            requestSchema: core.serialization.property(
                "request_schema",
                core.serialization.list(SchemaField).optional(),
            ),
            responseSchema: core.serialization.property(
                "response_schema",
                core.serialization.list(SchemaField).optional(),
            ),
        })
        .extend(RuleBase);

export declare namespace RuleDetail {
    export interface Raw extends RuleBase.Raw {
        created_at?: string | null;
        folder?: Folder.Raw | null;
        request_schema?: SchemaField.Raw[] | null;
        response_schema?: SchemaField.Raw[] | null;
    }
}
