/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { RuleDetail } from "./RuleDetail";
export declare const RuleListResponse: core.serialization.Schema<serializers.RuleListResponse.Raw, RulebricksApi.RuleListResponse>;
export declare namespace RuleListResponse {
    type Raw = RuleDetail.Raw[];
}
