/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { Folder } from "./Folder";
import { SchemaField } from "./SchemaField";
import { RuleBase } from "./RuleBase";
export declare const RuleDetail: core.serialization.ObjectSchema<serializers.RuleDetail.Raw, RulebricksApi.RuleDetail>;
export declare namespace RuleDetail {
    interface Raw extends RuleBase.Raw {
        created_at?: string | null;
        folder?: Folder.Raw | null;
        request_schema?: SchemaField.Raw[] | null;
        response_schema?: SchemaField.Raw[] | null;
    }
}
