/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { RuleDetail } from "./RuleDetail";

export const RuleListResponse: core.serialization.Schema<
    serializers.RuleListResponse.Raw,
    Rulebricks.RuleListResponse
> = core.serialization.list(RuleDetail);

export declare namespace RuleListResponse {
    export type Raw = RuleDetail.Raw[];
}
