/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const RuleExport: core.serialization.Schema<serializers.RuleExport.Raw, RulebricksApi.RuleExport>;
export declare namespace RuleExport {
    type Raw = Record<string, unknown>;
}
