/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const SchemaFieldDefaultValue: core.serialization.Schema<serializers.SchemaFieldDefaultValue.Raw, RulebricksApi.SchemaFieldDefaultValue>;
export declare namespace SchemaFieldDefaultValue {
    type Raw = string | number | boolean | Record<string, unknown> | unknown[];
}
