/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { SchemaFieldType } from "./SchemaFieldType";
import { SchemaFieldDefaultValue } from "./SchemaFieldDefaultValue";
export declare const SchemaField: core.serialization.ObjectSchema<serializers.SchemaField.Raw, RulebricksApi.SchemaField>;
export declare namespace SchemaField {
    interface Raw {
        key?: string | null;
        show?: boolean | null;
        name?: string | null;
        description?: string | null;
        type?: SchemaFieldType.Raw | null;
        defaultValue?: SchemaFieldDefaultValue.Raw | null;
        defaultComputedValue?: string | null;
        transform?: string | null;
    }
}
