/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const SuccessMessage: core.serialization.ObjectSchema<
    serializers.SuccessMessage.Raw,
    RulebricksApi.SuccessMessage
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace SuccessMessage {
    export interface Raw {
        message?: string | null;
    }
}
