/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { TestTestState } from "./TestTestState";
export declare const Test: core.serialization.ObjectSchema<serializers.Test.Raw, RulebricksApi.Test>;
export declare namespace Test {
    interface Raw {
        id: string;
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
        error: boolean;
        success: boolean;
        testState?: TestTestState.Raw | null;
        lastExecuted?: string | null;
    }
}
