/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const TestTestStateEvaluationError: core.serialization.Schema<
    serializers.TestTestStateEvaluationError.Raw,
    RulebricksApi.TestTestStateEvaluationError
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), core.serialization.string()]);

export declare namespace TestTestStateEvaluationError {
    export type Raw = boolean | string;
}
