/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";
import { Test } from "./Test";

export const TestListResponse: core.serialization.Schema<
    serializers.TestListResponse.Raw,
    Rulebricks.TestListResponse
> = core.serialization.list(Test);

export declare namespace TestListResponse {
    export type Raw = Test.Raw[];
}
