/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const UsageStatistics: core.serialization.ObjectSchema<serializers.UsageStatistics.Raw, RulebricksApi.UsageStatistics>;
export declare namespace UsageStatistics {
    interface Raw {
        plan?: string | null;
        monthly_period_start?: string | null;
        monthly_period_end?: string | null;
        monthly_executions_usage?: number | null;
        monthly_executions_limit?: number | null;
        monthly_executions_remaining?: number | null;
    }
}
