/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rulebricks from "../../api/index";
import * as core from "../../core";

export const UsageStatistics: core.serialization.ObjectSchema<
    serializers.UsageStatistics.Raw,
    Rulebricks.UsageStatistics
> = core.serialization.object({
    plan: core.serialization.string().optional(),
    monthlyPeriodStart: core.serialization.property("monthly_period_start", core.serialization.string().optional()),
    monthlyPeriodEnd: core.serialization.property("monthly_period_end", core.serialization.string().optional()),
    monthlyExecutionsUsage: core.serialization.property(
        "monthly_executions_usage",
        core.serialization.number().optional(),
    ),
    monthlyExecutionsLimit: core.serialization.property(
        "monthly_executions_limit",
        core.serialization.number().optional(),
    ),
    monthlyExecutionsRemaining: core.serialization.property(
        "monthly_executions_remaining",
        core.serialization.number().optional(),
    ),
});

export declare namespace UsageStatistics {
    export interface Raw {
        plan?: string | null;
        monthly_period_start?: string | null;
        monthly_period_end?: string | null;
        monthly_executions_usage?: number | null;
        monthly_executions_limit?: number | null;
        monthly_executions_remaining?: number | null;
    }
}
