/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
export declare const UserGroup: core.serialization.ObjectSchema<serializers.UserGroup.Raw, RulebricksApi.UserGroup>;
export declare namespace UserGroup {
    interface Raw {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        members?: string[] | null;
    }
}
