/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";
import { UserGroup } from "./UserGroup";

export const UserGroupListResponse: core.serialization.Schema<
    serializers.UserGroupListResponse.Raw,
    RulebricksApi.UserGroupListResponse
> = core.serialization.list(UserGroup);

export declare namespace UserGroupListResponse {
    export type Raw = UserGroup.Raw[];
}
