/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as RulebricksApi from "../../api/index";
import * as core from "../../core";

export const ValueLimits: core.serialization.ObjectSchema<serializers.ValueLimits.Raw, RulebricksApi.ValueLimits> =
    core.serialization.object({
        maxKeys: core.serialization.property("MAX_KEYS", core.serialization.number().optional()),
        maxValueLength: core.serialization.property("MAX_VALUE_LENGTH", core.serialization.number().optional()),
        maxTotalSize: core.serialization.property("MAX_TOTAL_SIZE", core.serialization.number().optional()),
        maxKeyLength: core.serialization.property("MAX_KEY_LENGTH", core.serialization.number().optional()),
    });

export declare namespace ValueLimits {
    export interface Raw {
        MAX_KEYS?: number | null;
        MAX_VALUE_LENGTH?: number | null;
        MAX_TOTAL_SIZE?: number | null;
        MAX_KEY_LENGTH?: number | null;
    }
}
