// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Marketing Rules",
 *         description: "Rules for marketing automation workflows"
 *     }
 */
export interface UpsertFolderRequest {
    /** Folder ID (required for updates, omit for creation) */
    id?: string;
    /** Name of the folder */
    name: string;
    /** Description of the folder */
    description?: string;
    /** The type of assets the folder organizes. Applies on creation; ignored when updating an existing folder. */
    type?: UpsertFolderRequest.Type;
}

export namespace UpsertFolderRequest {
    /** The type of assets the folder organizes. Applies on creation; ignored when updating an existing folder. */
    export const Type = {
        Rule: "rule",
        Flow: "flow",
        Context: "context",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
