/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as RulebricksApi from "../../../../api";
import * as core from "../../../../core";
export declare const Response: core.serialization.Schema<serializers.assets.listRules.Response.Raw, RulebricksApi.ListRulesResponseItem[]>;
export declare namespace Response {
    type Raw = serializers.ListRulesResponseItem.Raw[];
}
