/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as RulebricksApi from "../../../../api";
import * as core from "../../../../core";
export declare const UpdateRequestValue: core.serialization.Schema<serializers.UpdateRequestValue.Raw, RulebricksApi.UpdateRequestValue>;
export declare namespace UpdateRequestValue {
    type Raw = string | number | boolean | unknown[];
}
