/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as RulebricksApi from "../../../../api";
import * as core from "../../../../core";
export declare const UpdateResponseItemValue: core.serialization.Schema<serializers.UpdateResponseItemValue.Raw, RulebricksApi.UpdateResponseItemValue>;
export declare namespace UpdateResponseItemValue {
    type Raw = string | number | boolean | unknown[];
}
