/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as RulebricksApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateValuesRequestValuesValue: core.serialization.Schema<
    serializers.UpdateValuesRequestValuesValue.Raw,
    RulebricksApi.UpdateValuesRequestValuesValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.boolean(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace UpdateValuesRequestValuesValue {
    export type Raw = string | number | boolean | string[];
}
