// This file was auto-generated by Fern from our API Definition.

export const DeleteObjectsRequestValues = {
    Archive: "archive",
    Detach: "detach",
} as const;
export type DeleteObjectsRequestValues = (typeof DeleteObjectsRequestValues)[keyof typeof DeleteObjectsRequestValues];
