/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as RulebricksApi from "../../../../api/index";
import * as core from "../../../../core";

export const UserInviteRequestRole: core.serialization.Schema<
    serializers.UserInviteRequestRole.Raw,
    RulebricksApi.UserInviteRequestRole
> = core.serialization.enum_(["admin", "editor", "developer", "custom-role"]);

export declare namespace UserInviteRequestRole {
    export type Raw = "admin" | "editor" | "developer" | "custom-role";
}
