/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as RulebricksApi from "../../../../api";
import * as core from "../../../../core";
export declare const Response: core.serialization.Schema<serializers.values.listDynamicValues.Response.Raw, RulebricksApi.ListDynamicValuesResponseItem[]>;
export declare namespace Response {
    type Raw = serializers.ListDynamicValuesResponseItem.Raw[];
}
