// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Rulebricks from "../../../../../index.js";

export declare namespace FlowsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FlowsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FlowsClient.Options>;

    constructor(options: FlowsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves a list of tests associated with the flow identified by the slug.
     *
     * @param {Rulebricks.tests.ListFlowsRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.list({
     *         slug: "slug"
     *     })
     */
    public list(
        request: Rulebricks.tests.ListFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Rulebricks.TestListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Rulebricks.tests.ListFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Rulebricks.TestListResponse>> {
        const { slug } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${core.url.encodePathParam(slug)}/tests`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Rulebricks.TestListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/admin/flows/{slug}/tests");
    }

    /**
     * Adds a new test to the test suite of a flow identified by the slug.
     *
     * @param {Rulebricks.tests.CreateFlowsRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.BadRequestError}
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.create({
     *         slug: "slug",
     *         body: {
     *             name: "Test 3",
     *             request: {
     *                 "param1": "value1"
     *             },
     *             response: {
     *                 "status": "success"
     *             },
     *             critical: true
     *         }
     *     })
     */
    public create(
        request: Rulebricks.tests.CreateFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Rulebricks.Test> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Rulebricks.tests.CreateFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Rulebricks.Test>> {
        const { slug, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${core.url.encodePathParam(slug)}/tests`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Rulebricks.Test, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Rulebricks.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/admin/flows/{slug}/tests");
    }

    /**
     * Deletes a test from the test suite of a flow identified by the slug.
     *
     * @param {Rulebricks.tests.DeleteFlowsRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.delete({
     *         slug: "slug",
     *         testId: "testId"
     *     })
     */
    public delete(
        request: Rulebricks.tests.DeleteFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Rulebricks.Test> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Rulebricks.tests.DeleteFlowsRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Rulebricks.Test>> {
        const { slug, testId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${core.url.encodePathParam(slug)}/tests/${core.url.encodePathParam(testId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Rulebricks.Test, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/admin/flows/{slug}/tests/{testId}",
        );
    }
}
