/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Rulebricks from "../../../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../../../serialization/index";
import * as errors from "../../../../../../errors/index";

export declare namespace Flows {
    export interface Options {
        environment?: core.Supplier<environments.RulebricksEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Flows {
    constructor(protected readonly _options: Flows.Options) {}

    /**
     * Retrieves a list of tests associated with the flow identified by the slug.
     *
     * @param {string} slug - The unique identifier for the resource.
     * @param {Flows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.list("slug")
     */
    public async list(slug: string, requestOptions?: Flows.RequestOptions): Promise<Rulebricks.TestListResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${encodeURIComponent(slug)}/tests`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.TestListResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RulebricksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.RulebricksTimeoutError("Timeout exceeded when calling GET /admin/flows/{slug}/tests.");
            case "unknown":
                throw new errors.RulebricksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Adds a new test to the test suite of a flow identified by the slug.
     *
     * @param {string} slug - The unique identifier for the resource.
     * @param {Rulebricks.CreateTestRequest} request
     * @param {Flows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.BadRequestError}
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.create("slug", {
     *         name: "Test 3",
     *         request: {
     *             "param1": "value1"
     *         },
     *         response: {
     *             "status": "success"
     *         },
     *         critical: true
     *     })
     */
    public async create(
        slug: string,
        request: Rulebricks.CreateTestRequest,
        requestOptions?: Flows.RequestOptions,
    ): Promise<Rulebricks.Test> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${encodeURIComponent(slug)}/tests`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.CreateTestRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Test.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Rulebricks.BadRequestError(_response.error.body);
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RulebricksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.RulebricksTimeoutError(
                    "Timeout exceeded when calling POST /admin/flows/{slug}/tests.",
                );
            case "unknown":
                throw new errors.RulebricksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Deletes a test from the test suite of a flow identified by the slug.
     *
     * @param {string} slug - The unique identifier for the resource.
     * @param {string} testId - The ID of the test.
     * @param {Flows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Rulebricks.NotFoundError}
     * @throws {@link Rulebricks.InternalServerError}
     *
     * @example
     *     await client.tests.flows.delete("slug", "testId")
     */
    public async delete(slug: string, testId: string, requestOptions?: Flows.RequestOptions): Promise<Rulebricks.Test> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RulebricksEnvironment.Default,
                `admin/flows/${encodeURIComponent(slug)}/tests/${encodeURIComponent(testId)}`,
            ),
            method: "DELETE",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Test.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Rulebricks.NotFoundError(_response.error.body);
                case 500:
                    throw new Rulebricks.InternalServerError(_response.error.body);
                default:
                    throw new errors.RulebricksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RulebricksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.RulebricksTimeoutError(
                    "Timeout exceeded when calling DELETE /admin/flows/{slug}/tests/{testId}.",
                );
            case "unknown":
                throw new errors.RulebricksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
