/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core";
import { Rules } from "./api/resources/rules/client/Client";
import { Flows } from "./api/resources/flows/client/Client";
import { Decisions } from "./api/resources/decisions/client/Client";
import { Assets } from "./api/resources/assets/client/Client";
import { Users } from "./api/resources/users/client/Client";
import { Tests } from "./api/resources/tests/client/Client";
import { Values } from "./api/resources/values/client/Client";
export declare namespace RulebricksApiClient {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class RulebricksApiClient {
    protected readonly _options: RulebricksApiClient.Options;
    protected _rules: Rules | undefined;
    protected _flows: Flows | undefined;
    protected _decisions: Decisions | undefined;
    protected _assets: Assets | undefined;
    protected _users: Users | undefined;
    protected _tests: Tests | undefined;
    protected _values: Values | undefined;
    constructor(_options: RulebricksApiClient.Options);
    get rules(): Rules;
    get flows(): Flows;
    get decisions(): Decisions;
    get assets(): Assets;
    get users(): Users;
    get tests(): Tests;
    get values(): Values;
}
