/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core";
import { Rules } from "./api/resources/rules/client/Client";
import { Flows } from "./api/resources/flows/client/Client";
export declare namespace RulebricksClient {
    interface Options {
        environment: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class RulebricksClient {
    protected readonly _options: RulebricksClient.Options;
    constructor(_options: RulebricksClient.Options);
    protected _rules: Rules | undefined;
    get rules(): Rules;
    protected _flows: Flows | undefined;
    get flows(): Flows;
}
