"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RulebricksApiClient = void 0;
const Client_1 = require("./api/resources/rules/client/Client");
const Client_2 = require("./api/resources/flows/client/Client");
const Client_3 = require("./api/resources/decisions/client/Client");
const Client_4 = require("./api/resources/assets/client/Client");
const Client_5 = require("./api/resources/users/client/Client");
const Client_6 = require("./api/resources/tests/client/Client");
const Client_7 = require("./api/resources/values/client/Client");
class RulebricksApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get rules() {
        var _a;
        return ((_a = this._rules) !== null && _a !== void 0 ? _a : (this._rules = new Client_1.Rules(this._options)));
    }
    get flows() {
        var _a;
        return ((_a = this._flows) !== null && _a !== void 0 ? _a : (this._flows = new Client_2.Flows(this._options)));
    }
    get decisions() {
        var _a;
        return ((_a = this._decisions) !== null && _a !== void 0 ? _a : (this._decisions = new Client_3.Decisions(this._options)));
    }
    get assets() {
        var _a;
        return ((_a = this._assets) !== null && _a !== void 0 ? _a : (this._assets = new Client_4.Assets(this._options)));
    }
    get users() {
        var _a;
        return ((_a = this._users) !== null && _a !== void 0 ? _a : (this._users = new Client_5.Users(this._options)));
    }
    get tests() {
        var _a;
        return ((_a = this._tests) !== null && _a !== void 0 ? _a : (this._tests = new Client_6.Tests(this._options)));
    }
    get values() {
        var _a;
        return ((_a = this._values) !== null && _a !== void 0 ? _a : (this._values = new Client_7.Values(this._options)));
    }
}
exports.RulebricksApiClient = RulebricksApiClient;
