// This file was auto-generated by Fern from our API Definition.

import { AssetsClient } from "./api/resources/assets/client/Client.js";
import { ContextsClient } from "./api/resources/contexts/client/Client.js";
import { DecisionsClient } from "./api/resources/decisions/client/Client.js";
import { FlowsClient } from "./api/resources/flows/client/Client.js";
import { RulesClient } from "./api/resources/rules/client/Client.js";
import { TestsClient } from "./api/resources/tests/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import { ValuesClient } from "./api/resources/values/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace RulebricksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RulebricksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RulebricksClient.Options>;
    protected _rules: RulesClient | undefined;
    protected _flows: FlowsClient | undefined;
    protected _decisions: DecisionsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _assets: AssetsClient | undefined;
    protected _values: ValuesClient | undefined;
    protected _contexts: ContextsClient | undefined;
    protected _tests: TestsClient | undefined;

    constructor(options: RulebricksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get rules(): RulesClient {
        return (this._rules ??= new RulesClient(this._options));
    }

    public get flows(): FlowsClient {
        return (this._flows ??= new FlowsClient(this._options));
    }

    public get decisions(): DecisionsClient {
        return (this._decisions ??= new DecisionsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get assets(): AssetsClient {
        return (this._assets ??= new AssetsClient(this._options));
    }

    public get values(): ValuesClient {
        return (this._values ??= new ValuesClient(this._options));
    }

    public get contexts(): ContextsClient {
        return (this._contexts ??= new ContextsClient(this._options));
    }

    public get tests(): TestsClient {
        return (this._tests ??= new TestsClient(this._options));
    }
}
