/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RulebricksEnvironment = {
    Default: "https://rulebricks.com/api/v1",
} as const;

export type RulebricksEnvironment = typeof RulebricksEnvironment.Default;
