/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as core from "../../../../core";
export declare const Request: core.serialization.Schema<serializers.rules.parallelSolve.Request.Raw, Record<string, unknown>>;
export declare namespace Request {
    type Raw = Record<string, unknown>;
}
export declare const Response: core.serialization.Schema<serializers.rules.parallelSolve.Response.Raw, Record<string, unknown>>;
export declare namespace Response {
    type Raw = Record<string, unknown>;
}
