/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RulebricksApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const CreateRuleTestRequest: core.serialization.Schema<serializers.CreateRuleTestRequest.Raw, RulebricksApi.CreateRuleTestRequest>;
export declare namespace CreateRuleTestRequest {
    interface Raw {
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
    }
}
