/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RulebricksApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const CreateTestRequest: core.serialization.Schema<serializers.CreateTestRequest.Raw, RulebricksApi.CreateTestRequest>;
export declare namespace CreateTestRequest {
    interface Raw {
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
    }
}
