/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RulebricksApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const CreateFlowTestRequest: core.serialization.Schema<serializers.CreateFlowTestRequest.Raw, RulebricksApi.CreateFlowTestRequest>;
export declare namespace CreateFlowTestRequest {
    interface Raw {
        name: string;
        request: Record<string, unknown>;
        response: Record<string, unknown>;
        critical: boolean;
    }
}
