/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as RulebricksApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateValuesRequestValuesValue } from "../../types/UpdateValuesRequestValuesValue";
export declare const UpdateValuesRequest: core.serialization.Schema<serializers.UpdateValuesRequest.Raw, RulebricksApi.UpdateValuesRequest>;
export declare namespace UpdateValuesRequest {
    interface Raw {
        values: Record<string, UpdateValuesRequestValuesValue.Raw>;
        accessGroups?: string[] | null;
    }
}
