// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Claim",
 *         content: "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"countryCode\": { \"type\": \"string\", \"title\": \"Country Code\", \"enum\": [\"US\", \"CA\", \"GB\"] }\n  }\n}",
 *         user_groups: ["underwriting"]
 *     }
 */
export interface UpsertObjectRequest {
    /** Object ID to update. Omit to resolve by name (creating the object when the name is new). */
    id?: string;
    /** Object name. Required when ID is omitted; used to resolve the existing object or to name a new one. */
    name?: string;
    /** The object's JSON Schema as a string. Enums in the schema become the object's managed values. */
    content: string;
    /** User groups for the object, propagated to every value it generates. Omit to keep the current groups. */
    user_groups?: string[];
    /** Preview the value diff (would_sync / would_archive) without writing anything. */
    dry_run?: boolean;
    /** Optimistic concurrency: reject with 409 when the object's updated_at no longer matches. */
    expected_updated_at?: string;
}
